// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewAuthenticablePtr creates a new instance of AuthenticablePtr. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuthenticablePtr[T any](t interface {
	mock.TestingT
	Cleanup(func())
}) *AuthenticablePtr[T] {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &AuthenticablePtr[T]{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// AuthenticablePtr is an autogenerated mock type for the AuthenticablePtr type
type AuthenticablePtr[T any] struct {
	mock.Mock
}

type AuthenticablePtr_Expecter[T any] struct {
	mock *mock.Mock
}

func (_m *AuthenticablePtr[T]) EXPECT() *AuthenticablePtr_Expecter[T] {
	return &AuthenticablePtr_Expecter[T]{mock: &_m.Mock}
}

// Active provides a mock function for the type AuthenticablePtr
func (_mock *AuthenticablePtr[T]) Active() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Active")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// AuthenticablePtr_Active_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Active'
type AuthenticablePtr_Active_Call[T any] struct {
	*mock.Call
}

// Active is a helper method to define mock.On call
func (_e *AuthenticablePtr_Expecter[T]) Active() *AuthenticablePtr_Active_Call[T] {
	return &AuthenticablePtr_Active_Call[T]{Call: _e.mock.On("Active")}
}

func (_c *AuthenticablePtr_Active_Call[T]) Run(run func()) *AuthenticablePtr_Active_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *AuthenticablePtr_Active_Call[T]) Return(err error) *AuthenticablePtr_Active_Call[T] {
	_c.Call.Return(err)
	return _c
}

func (_c *AuthenticablePtr_Active_Call[T]) RunAndReturn(run func() error) *AuthenticablePtr_Active_Call[T] {
	_c.Call.Return(run)
	return _c
}

// Login provides a mock function for the type AuthenticablePtr
func (_mock *AuthenticablePtr[T]) Login() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// AuthenticablePtr_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type AuthenticablePtr_Login_Call[T any] struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
func (_e *AuthenticablePtr_Expecter[T]) Login() *AuthenticablePtr_Login_Call[T] {
	return &AuthenticablePtr_Login_Call[T]{Call: _e.mock.On("Login")}
}

func (_c *AuthenticablePtr_Login_Call[T]) Run(run func()) *AuthenticablePtr_Login_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *AuthenticablePtr_Login_Call[T]) Return(s string) *AuthenticablePtr_Login_Call[T] {
	_c.Call.Return(s)
	return _c
}

func (_c *AuthenticablePtr_Login_Call[T]) RunAndReturn(run func() string) *AuthenticablePtr_Login_Call[T] {
	_c.Call.Return(run)
	return _c
}

// Password provides a mock function for the type AuthenticablePtr
func (_mock *AuthenticablePtr[T]) Password() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Password")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// AuthenticablePtr_Password_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Password'
type AuthenticablePtr_Password_Call[T any] struct {
	*mock.Call
}

// Password is a helper method to define mock.On call
func (_e *AuthenticablePtr_Expecter[T]) Password() *AuthenticablePtr_Password_Call[T] {
	return &AuthenticablePtr_Password_Call[T]{Call: _e.mock.On("Password")}
}

func (_c *AuthenticablePtr_Password_Call[T]) Run(run func()) *AuthenticablePtr_Password_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *AuthenticablePtr_Password_Call[T]) Return(s string) *AuthenticablePtr_Password_Call[T] {
	_c.Call.Return(s)
	return _c
}

func (_c *AuthenticablePtr_Password_Call[T]) RunAndReturn(run func() string) *AuthenticablePtr_Password_Call[T] {
	_c.Call.Return(run)
	return _c
}

// SetPassword provides a mock function for the type AuthenticablePtr
func (_mock *AuthenticablePtr[T]) SetPassword(s string) {
	_mock.Called(s)
	return
}

// AuthenticablePtr_SetPassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetPassword'
type AuthenticablePtr_SetPassword_Call[T any] struct {
	*mock.Call
}

// SetPassword is a helper method to define mock.On call
//   - s string
func (_e *AuthenticablePtr_Expecter[T]) SetPassword(s any) *AuthenticablePtr_SetPassword_Call[T] {
	return &AuthenticablePtr_SetPassword_Call[T]{Call: _e.mock.On("SetPassword", s)}
}

func (_c *AuthenticablePtr_SetPassword_Call[T]) Run(run func(s string)) *AuthenticablePtr_SetPassword_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *AuthenticablePtr_SetPassword_Call[T]) Return() *AuthenticablePtr_SetPassword_Call[T] {
	_c.Call.Return()
	return _c
}

func (_c *AuthenticablePtr_SetPassword_Call[T]) RunAndReturn(run func(s string)) *AuthenticablePtr_SetPassword_Call[T] {
	_c.Run(run)
	return _c
}
