// Code generated by mockery v2.33.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// AuthenticablePtr is an autogenerated mock type for the AuthenticablePtr type
type AuthenticablePtr[T interface{}] struct {
	mock.Mock
}

type AuthenticablePtr_Expecter[T interface{}] struct {
	mock *mock.Mock
}

func (_m *AuthenticablePtr[T]) EXPECT() *AuthenticablePtr_Expecter[T] {
	return &AuthenticablePtr_Expecter[T]{mock: &_m.Mock}
}

// ChangePasswordRequired provides a mock function with given fields:
func (_m *AuthenticablePtr[T]) ChangePasswordRequired() bool {
	ret := _m.Called()

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// AuthenticablePtr_ChangePasswordRequired_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ChangePasswordRequired'
type AuthenticablePtr_ChangePasswordRequired_Call[T interface{}] struct {
	*mock.Call
}

// ChangePasswordRequired is a helper method to define mock.On call
func (_e *AuthenticablePtr_Expecter[T]) ChangePasswordRequired() *AuthenticablePtr_ChangePasswordRequired_Call[T] {
	return &AuthenticablePtr_ChangePasswordRequired_Call[T]{Call: _e.mock.On("ChangePasswordRequired")}
}

func (_c *AuthenticablePtr_ChangePasswordRequired_Call[T]) Run(run func()) *AuthenticablePtr_ChangePasswordRequired_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *AuthenticablePtr_ChangePasswordRequired_Call[T]) Return(_a0 bool) *AuthenticablePtr_ChangePasswordRequired_Call[T] {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AuthenticablePtr_ChangePasswordRequired_Call[T]) RunAndReturn(run func() bool) *AuthenticablePtr_ChangePasswordRequired_Call[T] {
	_c.Call.Return(run)
	return _c
}

// Login provides a mock function with given fields:
func (_m *AuthenticablePtr[T]) Login() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// AuthenticablePtr_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type AuthenticablePtr_Login_Call[T interface{}] struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
func (_e *AuthenticablePtr_Expecter[T]) Login() *AuthenticablePtr_Login_Call[T] {
	return &AuthenticablePtr_Login_Call[T]{Call: _e.mock.On("Login")}
}

func (_c *AuthenticablePtr_Login_Call[T]) Run(run func()) *AuthenticablePtr_Login_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *AuthenticablePtr_Login_Call[T]) Return(_a0 string) *AuthenticablePtr_Login_Call[T] {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AuthenticablePtr_Login_Call[T]) RunAndReturn(run func() string) *AuthenticablePtr_Login_Call[T] {
	_c.Call.Return(run)
	return _c
}

// Password provides a mock function with given fields:
func (_m *AuthenticablePtr[T]) Password() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// AuthenticablePtr_Password_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Password'
type AuthenticablePtr_Password_Call[T interface{}] struct {
	*mock.Call
}

// Password is a helper method to define mock.On call
func (_e *AuthenticablePtr_Expecter[T]) Password() *AuthenticablePtr_Password_Call[T] {
	return &AuthenticablePtr_Password_Call[T]{Call: _e.mock.On("Password")}
}

func (_c *AuthenticablePtr_Password_Call[T]) Run(run func()) *AuthenticablePtr_Password_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *AuthenticablePtr_Password_Call[T]) Return(_a0 string) *AuthenticablePtr_Password_Call[T] {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AuthenticablePtr_Password_Call[T]) RunAndReturn(run func() string) *AuthenticablePtr_Password_Call[T] {
	_c.Call.Return(run)
	return _c
}

// SetPassword provides a mock function with given fields: _a0
func (_m *AuthenticablePtr[T]) SetPassword(_a0 string) {
	_m.Called(_a0)
}

// AuthenticablePtr_SetPassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetPassword'
type AuthenticablePtr_SetPassword_Call[T interface{}] struct {
	*mock.Call
}

// SetPassword is a helper method to define mock.On call
//   - _a0 string
func (_e *AuthenticablePtr_Expecter[T]) SetPassword(_a0 interface{}) *AuthenticablePtr_SetPassword_Call[T] {
	return &AuthenticablePtr_SetPassword_Call[T]{Call: _e.mock.On("SetPassword", _a0)}
}

func (_c *AuthenticablePtr_SetPassword_Call[T]) Run(run func(_a0 string)) *AuthenticablePtr_SetPassword_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *AuthenticablePtr_SetPassword_Call[T]) Return() *AuthenticablePtr_SetPassword_Call[T] {
	_c.Call.Return()
	return _c
}

func (_c *AuthenticablePtr_SetPassword_Call[T]) RunAndReturn(run func(string)) *AuthenticablePtr_SetPassword_Call[T] {
	_c.Call.Return(run)
	return _c
}

// NewAuthenticablePtr creates a new instance of AuthenticablePtr. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuthenticablePtr[T interface{}](t interface {
	mock.TestingT
	Cleanup(func())
}) *AuthenticablePtr[T] {
	mock := &AuthenticablePtr[T]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
