// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewAuthenticable creates a new instance of Authenticable. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuthenticable(t interface {
	mock.TestingT
	Cleanup(func())
}) *Authenticable {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &Authenticable{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// Authenticable is an autogenerated mock type for the Authenticable type
type Authenticable struct {
	mock.Mock
}

type Authenticable_Expecter struct {
	mock *mock.Mock
}

func (_m *Authenticable) EXPECT() *Authenticable_Expecter {
	return &Authenticable_Expecter{mock: &_m.Mock}
}

// Active provides a mock function for the type Authenticable
func (_mock *Authenticable) Active() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Active")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Authenticable_Active_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Active'
type Authenticable_Active_Call struct {
	*mock.Call
}

// Active is a helper method to define mock.On call
func (_e *Authenticable_Expecter) Active() *Authenticable_Active_Call {
	return &Authenticable_Active_Call{Call: _e.mock.On("Active")}
}

func (_c *Authenticable_Active_Call) Run(run func()) *Authenticable_Active_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Authenticable_Active_Call) Return(err error) *Authenticable_Active_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Authenticable_Active_Call) RunAndReturn(run func() error) *Authenticable_Active_Call {
	_c.Call.Return(run)
	return _c
}

// Login provides a mock function for the type Authenticable
func (_mock *Authenticable) Login() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// Authenticable_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type Authenticable_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
func (_e *Authenticable_Expecter) Login() *Authenticable_Login_Call {
	return &Authenticable_Login_Call{Call: _e.mock.On("Login")}
}

func (_c *Authenticable_Login_Call) Run(run func()) *Authenticable_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Authenticable_Login_Call) Return(s string) *Authenticable_Login_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *Authenticable_Login_Call) RunAndReturn(run func() string) *Authenticable_Login_Call {
	_c.Call.Return(run)
	return _c
}

// Password provides a mock function for the type Authenticable
func (_mock *Authenticable) Password() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Password")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// Authenticable_Password_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Password'
type Authenticable_Password_Call struct {
	*mock.Call
}

// Password is a helper method to define mock.On call
func (_e *Authenticable_Expecter) Password() *Authenticable_Password_Call {
	return &Authenticable_Password_Call{Call: _e.mock.On("Password")}
}

func (_c *Authenticable_Password_Call) Run(run func()) *Authenticable_Password_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Authenticable_Password_Call) Return(s string) *Authenticable_Password_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *Authenticable_Password_Call) RunAndReturn(run func() string) *Authenticable_Password_Call {
	_c.Call.Return(run)
	return _c
}

// SetPassword provides a mock function for the type Authenticable
func (_mock *Authenticable) SetPassword(s string) {
	_mock.Called(s)
	return
}

// Authenticable_SetPassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetPassword'
type Authenticable_SetPassword_Call struct {
	*mock.Call
}

// SetPassword is a helper method to define mock.On call
//   - s string
func (_e *Authenticable_Expecter) SetPassword(s any) *Authenticable_SetPassword_Call {
	return &Authenticable_SetPassword_Call{Call: _e.mock.On("SetPassword", s)}
}

func (_c *Authenticable_SetPassword_Call) Run(run func(s string)) *Authenticable_SetPassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Authenticable_SetPassword_Call) Return() *Authenticable_SetPassword_Call {
	_c.Call.Return()
	return _c
}

func (_c *Authenticable_SetPassword_Call) RunAndReturn(run func(s string)) *Authenticable_SetPassword_Call {
	_c.Run(run)
	return _c
}
