// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/bldsoft/gost/repository"
	mock "github.com/stretchr/testify/mock"
)

// NewIAuthRepository creates a new instance of IAuthRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIAuthRepository[PT any](t interface {
	mock.TestingT
	Cleanup(func())
}) *IAuthRepository[PT] {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &IAuthRepository[PT]{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// IAuthRepository is an autogenerated mock type for the IAuthRepository type
type IAuthRepository[PT any] struct {
	mock.Mock
}

type IAuthRepository_Expecter[PT any] struct {
	mock *mock.Mock
}

func (_m *IAuthRepository[PT]) EXPECT() *IAuthRepository_Expecter[PT] {
	return &IAuthRepository_Expecter[PT]{mock: &_m.Mock}
}

// FindByLogin provides a mock function for the type IAuthRepository
func (_mock *IAuthRepository[PT]) FindByLogin(ctx context.Context, login string, options ...*repository.QueryOptions) (PT, error) {
	var tmpRet mock.Arguments
	if len(options) > 0 {
		tmpRet = _mock.Called(ctx, login, options)
	} else {
		tmpRet = _mock.Called(ctx, login)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for FindByLogin")
	}

	var r0 PT
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...*repository.QueryOptions) (PT, error)); ok {
		return returnFunc(ctx, login, options...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...*repository.QueryOptions) PT); ok {
		r0 = returnFunc(ctx, login, options...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(PT)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, ...*repository.QueryOptions) error); ok {
		r1 = returnFunc(ctx, login, options...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// IAuthRepository_FindByLogin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByLogin'
type IAuthRepository_FindByLogin_Call[PT any] struct {
	*mock.Call
}

// FindByLogin is a helper method to define mock.On call
//   - ctx context.Context
//   - login string
//   - options ...*repository.QueryOptions
func (_e *IAuthRepository_Expecter[PT]) FindByLogin(ctx any, login any, options ...any) *IAuthRepository_FindByLogin_Call[PT] {
	return &IAuthRepository_FindByLogin_Call[PT]{Call: _e.mock.On("FindByLogin",
		append([]any{ctx, login}, options...)...)}
}

func (_c *IAuthRepository_FindByLogin_Call[PT]) Run(run func(ctx context.Context, login string, options ...*repository.QueryOptions)) *IAuthRepository_FindByLogin_Call[PT] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []*repository.QueryOptions
		var variadicArgs []*repository.QueryOptions
		if len(args) > 2 {
			variadicArgs = args[2].([]*repository.QueryOptions)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *IAuthRepository_FindByLogin_Call[PT]) Return(v PT, err error) *IAuthRepository_FindByLogin_Call[PT] {
	_c.Call.Return(v, err)
	return _c
}

func (_c *IAuthRepository_FindByLogin_Call[PT]) RunAndReturn(run func(ctx context.Context, login string, options ...*repository.QueryOptions) (PT, error)) *IAuthRepository_FindByLogin_Call[PT] {
	_c.Call.Return(run)
	return _c
}
