// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewIRole creates a new instance of IRole. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIRole(t interface {
	mock.TestingT
	Cleanup(func())
}) *IRole {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &IRole{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// IRole is an autogenerated mock type for the IRole type
type IRole struct {
	mock.Mock
}

type IRole_Expecter struct {
	mock *mock.Mock
}

func (_m *IRole) EXPECT() *IRole_Expecter {
	return &IRole_Expecter{mock: &_m.Mock}
}
