// Code generated by mockery v2.33.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// IRole is an autogenerated mock type for the IRole type
type IRole struct {
	mock.Mock
}

type IRole_Expecter struct {
	mock *mock.Mock
}

func (_m *IRole) EXPECT() *IRole_Expecter {
	return &IRole_Expecter{mock: &_m.Mock}
}

// NewIRole creates a new instance of IRole. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIRole(t interface {
	mock.TestingT
	Cleanup(func())
}) *IRole {
	mock := &IRole{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
