// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/bldsoft/gost/auth"
	mock "github.com/stretchr/testify/mock"
)

// NewIUserService creates a new instance of IUserService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIUserService[PT auth.AuthenticablePtr[T], T any](t interface {
	mock.TestingT
	Cleanup(func())
}) *IUserService[PT, T] {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &IUserService[PT, T]{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// IUserService is an autogenerated mock type for the IUserService type
type IUserService[PT auth.AuthenticablePtr[T], T any] struct {
	mock.Mock
}

type IUserService_Expecter[PT auth.AuthenticablePtr[T], T any] struct {
	mock *mock.Mock
}

func (_m *IUserService[PT, T]) EXPECT() *IUserService_Expecter[PT, T] {
	return &IUserService_Expecter[PT, T]{mock: &_m.Mock}
}

// Create provides a mock function for the type IUserService
func (_mock *IUserService[PT, T]) Create(ctx context.Context, user PT, recoverDeleted bool) error {
	ret := _mock.Called(ctx, user, recoverDeleted)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, PT, bool) error); ok {
		r0 = returnFunc(ctx, user, recoverDeleted)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// IUserService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type IUserService_Create_Call[PT auth.AuthenticablePtr[T], T any] struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - user PT
//   - recoverDeleted bool
func (_e *IUserService_Expecter[PT, T]) Create(ctx any, user any, recoverDeleted any) *IUserService_Create_Call[PT, T] {
	return &IUserService_Create_Call[PT, T]{Call: _e.mock.On("Create", ctx, user, recoverDeleted)}
}

func (_c *IUserService_Create_Call[PT, T]) Run(run func(ctx context.Context, user PT, recoverDeleted bool)) *IUserService_Create_Call[PT, T] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 PT
		if args[1] != nil {
			arg1 = args[1].(PT)
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *IUserService_Create_Call[PT, T]) Return(err error) *IUserService_Create_Call[PT, T] {
	_c.Call.Return(err)
	return _c
}

func (_c *IUserService_Create_Call[PT, T]) RunAndReturn(run func(ctx context.Context, user PT, recoverDeleted bool) error) *IUserService_Create_Call[PT, T] {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type IUserService
func (_mock *IUserService[PT, T]) Delete(ctx context.Context, id string, archived bool) error {
	ret := _mock.Called(ctx, id, archived)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, bool) error); ok {
		r0 = returnFunc(ctx, id, archived)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// IUserService_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type IUserService_Delete_Call[PT auth.AuthenticablePtr[T], T any] struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - archived bool
func (_e *IUserService_Expecter[PT, T]) Delete(ctx any, id any, archived any) *IUserService_Delete_Call[PT, T] {
	return &IUserService_Delete_Call[PT, T]{Call: _e.mock.On("Delete", ctx, id, archived)}
}

func (_c *IUserService_Delete_Call[PT, T]) Run(run func(ctx context.Context, id string, archived bool)) *IUserService_Delete_Call[PT, T] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *IUserService_Delete_Call[PT, T]) Return(err error) *IUserService_Delete_Call[PT, T] {
	_c.Call.Return(err)
	return _c
}

func (_c *IUserService_Delete_Call[PT, T]) RunAndReturn(run func(ctx context.Context, id string, archived bool) error) *IUserService_Delete_Call[PT, T] {
	_c.Call.Return(run)
	return _c
}

// GetAll provides a mock function for the type IUserService
func (_mock *IUserService[PT, T]) GetAll(ctx context.Context, archived bool) ([]PT, error) {
	ret := _mock.Called(ctx, archived)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []PT
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, bool) ([]PT, error)); ok {
		return returnFunc(ctx, archived)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, bool) []PT); ok {
		r0 = returnFunc(ctx, archived)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]PT)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, bool) error); ok {
		r1 = returnFunc(ctx, archived)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// IUserService_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type IUserService_GetAll_Call[PT auth.AuthenticablePtr[T], T any] struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
//   - ctx context.Context
//   - archived bool
func (_e *IUserService_Expecter[PT, T]) GetAll(ctx any, archived any) *IUserService_GetAll_Call[PT, T] {
	return &IUserService_GetAll_Call[PT, T]{Call: _e.mock.On("GetAll", ctx, archived)}
}

func (_c *IUserService_GetAll_Call[PT, T]) Run(run func(ctx context.Context, archived bool)) *IUserService_GetAll_Call[PT, T] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 bool
		if args[1] != nil {
			arg1 = args[1].(bool)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *IUserService_GetAll_Call[PT, T]) Return(vs []PT, err error) *IUserService_GetAll_Call[PT, T] {
	_c.Call.Return(vs, err)
	return _c
}

func (_c *IUserService_GetAll_Call[PT, T]) RunAndReturn(run func(ctx context.Context, archived bool) ([]PT, error)) *IUserService_GetAll_Call[PT, T] {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type IUserService
func (_mock *IUserService[PT, T]) GetByID(ctx context.Context, id string) (PT, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 PT
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (PT, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) PT); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(PT)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// IUserService_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type IUserService_GetByID_Call[PT auth.AuthenticablePtr[T], T any] struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *IUserService_Expecter[PT, T]) GetByID(ctx any, id any) *IUserService_GetByID_Call[PT, T] {
	return &IUserService_GetByID_Call[PT, T]{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *IUserService_GetByID_Call[PT, T]) Run(run func(ctx context.Context, id string)) *IUserService_GetByID_Call[PT, T] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *IUserService_GetByID_Call[PT, T]) Return(v PT, err error) *IUserService_GetByID_Call[PT, T] {
	_c.Call.Return(v, err)
	return _c
}

func (_c *IUserService_GetByID_Call[PT, T]) RunAndReturn(run func(ctx context.Context, id string) (PT, error)) *IUserService_GetByID_Call[PT, T] {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type IUserService
func (_mock *IUserService[PT, T]) Update(ctx context.Context, user PT) error {
	ret := _mock.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, PT) error); ok {
		r0 = returnFunc(ctx, user)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// IUserService_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type IUserService_Update_Call[PT auth.AuthenticablePtr[T], T any] struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - user PT
func (_e *IUserService_Expecter[PT, T]) Update(ctx any, user any) *IUserService_Update_Call[PT, T] {
	return &IUserService_Update_Call[PT, T]{Call: _e.mock.On("Update", ctx, user)}
}

func (_c *IUserService_Update_Call[PT, T]) Run(run func(ctx context.Context, user PT)) *IUserService_Update_Call[PT, T] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 PT
		if args[1] != nil {
			arg1 = args[1].(PT)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *IUserService_Update_Call[PT, T]) Return(err error) *IUserService_Update_Call[PT, T] {
	_c.Call.Return(err)
	return _c
}

func (_c *IUserService_Update_Call[PT, T]) RunAndReturn(run func(ctx context.Context, user PT) error) *IUserService_Update_Call[PT, T] {
	_c.Call.Return(run)
	return _c
}

// UpdatePassword provides a mock function for the type IUserService
func (_mock *IUserService[PT, T]) UpdatePassword(ctx context.Context, id string, password string) error {
	ret := _mock.Called(ctx, id, password)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePassword")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, id, password)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// IUserService_UpdatePassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdatePassword'
type IUserService_UpdatePassword_Call[PT auth.AuthenticablePtr[T], T any] struct {
	*mock.Call
}

// UpdatePassword is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - password string
func (_e *IUserService_Expecter[PT, T]) UpdatePassword(ctx any, id any, password any) *IUserService_UpdatePassword_Call[PT, T] {
	return &IUserService_UpdatePassword_Call[PT, T]{Call: _e.mock.On("UpdatePassword", ctx, id, password)}
}

func (_c *IUserService_UpdatePassword_Call[PT, T]) Run(run func(ctx context.Context, id string, password string)) *IUserService_UpdatePassword_Call[PT, T] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *IUserService_UpdatePassword_Call[PT, T]) Return(err error) *IUserService_UpdatePassword_Call[PT, T] {
	_c.Call.Return(err)
	return _c
}

func (_c *IUserService_UpdatePassword_Call[PT, T]) RunAndReturn(run func(ctx context.Context, id string, password string) error) *IUserService_UpdatePassword_Call[PT, T] {
	_c.Call.Return(run)
	return _c
}
