// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/bldsoft/gost/repository"
	mock "github.com/stretchr/testify/mock"
)

// NewIUserRepository creates a new instance of IUserRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIUserRepository[PT any](t interface {
	mock.TestingT
	Cleanup(func())
}) *IUserRepository[PT] {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &IUserRepository[PT]{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// IUserRepository is an autogenerated mock type for the IUserRepository type
type IUserRepository[PT any] struct {
	mock.Mock
}

type IUserRepository_Expecter[PT any] struct {
	mock *mock.Mock
}

func (_m *IUserRepository[PT]) EXPECT() *IUserRepository_Expecter[PT] {
	return &IUserRepository_Expecter[PT]{mock: &_m.Mock}
}

// Delete provides a mock function for the type IUserRepository
func (_mock *IUserRepository[PT]) Delete(ctx context.Context, id interface{}, options ...*repository.QueryOptions) error {
	var tmpRet mock.Arguments
	if len(options) > 0 {
		tmpRet = _mock.Called(ctx, id, options)
	} else {
		tmpRet = _mock.Called(ctx, id)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, interface{}, ...*repository.QueryOptions) error); ok {
		r0 = returnFunc(ctx, id, options...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// IUserRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type IUserRepository_Delete_Call[PT any] struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id interface{}
//   - options ...*repository.QueryOptions
func (_e *IUserRepository_Expecter[PT]) Delete(ctx any, id any, options ...any) *IUserRepository_Delete_Call[PT] {
	return &IUserRepository_Delete_Call[PT]{Call: _e.mock.On("Delete",
		append([]any{ctx, id}, options...)...)}
}

func (_c *IUserRepository_Delete_Call[PT]) Run(run func(ctx context.Context, id interface{}, options ...*repository.QueryOptions)) *IUserRepository_Delete_Call[PT] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 interface{}
		if args[1] != nil {
			arg1 = args[1].(interface{})
		}
		var arg2 []*repository.QueryOptions
		var variadicArgs []*repository.QueryOptions
		if len(args) > 2 {
			variadicArgs = args[2].([]*repository.QueryOptions)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *IUserRepository_Delete_Call[PT]) Return(err error) *IUserRepository_Delete_Call[PT] {
	_c.Call.Return(err)
	return _c
}

func (_c *IUserRepository_Delete_Call[PT]) RunAndReturn(run func(ctx context.Context, id interface{}, options ...*repository.QueryOptions) error) *IUserRepository_Delete_Call[PT] {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function for the type IUserRepository
func (_mock *IUserRepository[PT]) FindByID(ctx context.Context, id interface{}, options ...*repository.QueryOptions) (PT, error) {
	var tmpRet mock.Arguments
	if len(options) > 0 {
		tmpRet = _mock.Called(ctx, id, options)
	} else {
		tmpRet = _mock.Called(ctx, id)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 PT
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, interface{}, ...*repository.QueryOptions) (PT, error)); ok {
		return returnFunc(ctx, id, options...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, interface{}, ...*repository.QueryOptions) PT); ok {
		r0 = returnFunc(ctx, id, options...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(PT)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, interface{}, ...*repository.QueryOptions) error); ok {
		r1 = returnFunc(ctx, id, options...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// IUserRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type IUserRepository_FindByID_Call[PT any] struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id interface{}
//   - options ...*repository.QueryOptions
func (_e *IUserRepository_Expecter[PT]) FindByID(ctx any, id any, options ...any) *IUserRepository_FindByID_Call[PT] {
	return &IUserRepository_FindByID_Call[PT]{Call: _e.mock.On("FindByID",
		append([]any{ctx, id}, options...)...)}
}

func (_c *IUserRepository_FindByID_Call[PT]) Run(run func(ctx context.Context, id interface{}, options ...*repository.QueryOptions)) *IUserRepository_FindByID_Call[PT] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 interface{}
		if args[1] != nil {
			arg1 = args[1].(interface{})
		}
		var arg2 []*repository.QueryOptions
		var variadicArgs []*repository.QueryOptions
		if len(args) > 2 {
			variadicArgs = args[2].([]*repository.QueryOptions)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *IUserRepository_FindByID_Call[PT]) Return(v PT, err error) *IUserRepository_FindByID_Call[PT] {
	_c.Call.Return(v, err)
	return _c
}

func (_c *IUserRepository_FindByID_Call[PT]) RunAndReturn(run func(ctx context.Context, id interface{}, options ...*repository.QueryOptions) (PT, error)) *IUserRepository_FindByID_Call[PT] {
	_c.Call.Return(run)
	return _c
}

// GetAll provides a mock function for the type IUserRepository
func (_mock *IUserRepository[PT]) GetAll(ctx context.Context, options ...*repository.QueryOptions) ([]PT, error) {
	var tmpRet mock.Arguments
	if len(options) > 0 {
		tmpRet = _mock.Called(ctx, options)
	} else {
		tmpRet = _mock.Called(ctx)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []PT
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...*repository.QueryOptions) ([]PT, error)); ok {
		return returnFunc(ctx, options...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...*repository.QueryOptions) []PT); ok {
		r0 = returnFunc(ctx, options...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]PT)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ...*repository.QueryOptions) error); ok {
		r1 = returnFunc(ctx, options...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// IUserRepository_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type IUserRepository_GetAll_Call[PT any] struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
//   - ctx context.Context
//   - options ...*repository.QueryOptions
func (_e *IUserRepository_Expecter[PT]) GetAll(ctx any, options ...any) *IUserRepository_GetAll_Call[PT] {
	return &IUserRepository_GetAll_Call[PT]{Call: _e.mock.On("GetAll",
		append([]any{ctx}, options...)...)}
}

func (_c *IUserRepository_GetAll_Call[PT]) Run(run func(ctx context.Context, options ...*repository.QueryOptions)) *IUserRepository_GetAll_Call[PT] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []*repository.QueryOptions
		var variadicArgs []*repository.QueryOptions
		if len(args) > 1 {
			variadicArgs = args[1].([]*repository.QueryOptions)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *IUserRepository_GetAll_Call[PT]) Return(vs []PT, err error) *IUserRepository_GetAll_Call[PT] {
	_c.Call.Return(vs, err)
	return _c
}

func (_c *IUserRepository_GetAll_Call[PT]) RunAndReturn(run func(ctx context.Context, options ...*repository.QueryOptions) ([]PT, error)) *IUserRepository_GetAll_Call[PT] {
	_c.Call.Return(run)
	return _c
}

// Insert provides a mock function for the type IUserRepository
func (_mock *IUserRepository[PT]) Insert(ctx context.Context, user PT) error {
	ret := _mock.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for Insert")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, PT) error); ok {
		r0 = returnFunc(ctx, user)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// IUserRepository_Insert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Insert'
type IUserRepository_Insert_Call[PT any] struct {
	*mock.Call
}

// Insert is a helper method to define mock.On call
//   - ctx context.Context
//   - user PT
func (_e *IUserRepository_Expecter[PT]) Insert(ctx any, user any) *IUserRepository_Insert_Call[PT] {
	return &IUserRepository_Insert_Call[PT]{Call: _e.mock.On("Insert", ctx, user)}
}

func (_c *IUserRepository_Insert_Call[PT]) Run(run func(ctx context.Context, user PT)) *IUserRepository_Insert_Call[PT] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 PT
		if args[1] != nil {
			arg1 = args[1].(PT)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *IUserRepository_Insert_Call[PT]) Return(err error) *IUserRepository_Insert_Call[PT] {
	_c.Call.Return(err)
	return _c
}

func (_c *IUserRepository_Insert_Call[PT]) RunAndReturn(run func(ctx context.Context, user PT) error) *IUserRepository_Insert_Call[PT] {
	_c.Call.Return(run)
	return _c
}

// InsertOrRecover provides a mock function for the type IUserRepository
func (_mock *IUserRepository[PT]) InsertOrRecover(ctx context.Context, user PT) error {
	ret := _mock.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for InsertOrRecover")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, PT) error); ok {
		r0 = returnFunc(ctx, user)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// IUserRepository_InsertOrRecover_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertOrRecover'
type IUserRepository_InsertOrRecover_Call[PT any] struct {
	*mock.Call
}

// InsertOrRecover is a helper method to define mock.On call
//   - ctx context.Context
//   - user PT
func (_e *IUserRepository_Expecter[PT]) InsertOrRecover(ctx any, user any) *IUserRepository_InsertOrRecover_Call[PT] {
	return &IUserRepository_InsertOrRecover_Call[PT]{Call: _e.mock.On("InsertOrRecover", ctx, user)}
}

func (_c *IUserRepository_InsertOrRecover_Call[PT]) Run(run func(ctx context.Context, user PT)) *IUserRepository_InsertOrRecover_Call[PT] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 PT
		if args[1] != nil {
			arg1 = args[1].(PT)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *IUserRepository_InsertOrRecover_Call[PT]) Return(err error) *IUserRepository_InsertOrRecover_Call[PT] {
	_c.Call.Return(err)
	return _c
}

func (_c *IUserRepository_InsertOrRecover_Call[PT]) RunAndReturn(run func(ctx context.Context, user PT) error) *IUserRepository_InsertOrRecover_Call[PT] {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type IUserRepository
func (_mock *IUserRepository[PT]) Update(ctx context.Context, user PT, options ...*repository.QueryOptions) error {
	var tmpRet mock.Arguments
	if len(options) > 0 {
		tmpRet = _mock.Called(ctx, user, options)
	} else {
		tmpRet = _mock.Called(ctx, user)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, PT, ...*repository.QueryOptions) error); ok {
		r0 = returnFunc(ctx, user, options...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// IUserRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type IUserRepository_Update_Call[PT any] struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - user PT
//   - options ...*repository.QueryOptions
func (_e *IUserRepository_Expecter[PT]) Update(ctx any, user any, options ...any) *IUserRepository_Update_Call[PT] {
	return &IUserRepository_Update_Call[PT]{Call: _e.mock.On("Update",
		append([]any{ctx, user}, options...)...)}
}

func (_c *IUserRepository_Update_Call[PT]) Run(run func(ctx context.Context, user PT, options ...*repository.QueryOptions)) *IUserRepository_Update_Call[PT] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 PT
		if args[1] != nil {
			arg1 = args[1].(PT)
		}
		var arg2 []*repository.QueryOptions
		var variadicArgs []*repository.QueryOptions
		if len(args) > 2 {
			variadicArgs = args[2].([]*repository.QueryOptions)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *IUserRepository_Update_Call[PT]) Return(err error) *IUserRepository_Update_Call[PT] {
	_c.Call.Return(err)
	return _c
}

func (_c *IUserRepository_Update_Call[PT]) RunAndReturn(run func(ctx context.Context, user PT, options ...*repository.QueryOptions) error) *IUserRepository_Update_Call[PT] {
	_c.Call.Return(run)
	return _c
}
