// Code generated by mockery v2.33.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// KeyGenFunc is an autogenerated mock type for the KeyGenFunc type
type KeyGenFunc struct {
	mock.Mock
}

type KeyGenFunc_Expecter struct {
	mock *mock.Mock
}

func (_m *KeyGenFunc) EXPECT() *KeyGenFunc_Expecter {
	return &KeyGenFunc_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields:
func (_m *KeyGenFunc) Execute() (string, error) {
	ret := _m.Called()

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func() (string, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// KeyGenFunc_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type KeyGenFunc_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
func (_e *KeyGenFunc_Expecter) Execute() *KeyGenFunc_Execute_Call {
	return &KeyGenFunc_Execute_Call{Call: _e.mock.On("Execute")}
}

func (_c *KeyGenFunc_Execute_Call) Run(run func()) *KeyGenFunc_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *KeyGenFunc_Execute_Call) Return(_a0 string, _a1 error) *KeyGenFunc_Execute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *KeyGenFunc_Execute_Call) RunAndReturn(run func() (string, error)) *KeyGenFunc_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewKeyGenFunc creates a new instance of KeyGenFunc. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewKeyGenFunc(t interface {
	mock.TestingT
	Cleanup(func())
}) *KeyGenFunc {
	mock := &KeyGenFunc{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
