// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewPasswordHasher creates a new instance of PasswordHasher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPasswordHasher(t interface {
	mock.TestingT
	Cleanup(func())
}) *PasswordHasher {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &PasswordHasher{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// PasswordHasher is an autogenerated mock type for the PasswordHasher type
type PasswordHasher struct {
	mock.Mock
}

type PasswordHasher_Expecter struct {
	mock *mock.Mock
}

func (_m *PasswordHasher) EXPECT() *PasswordHasher_Expecter {
	return &PasswordHasher_Expecter{mock: &_m.Mock}
}

// HashAndSalt provides a mock function for the type PasswordHasher
func (_mock *PasswordHasher) HashAndSalt(password string) (string, error) {
	ret := _mock.Called(password)

	if len(ret) == 0 {
		panic("no return value specified for HashAndSalt")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (string, error)); ok {
		return returnFunc(password)
	}
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(password)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(password)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// PasswordHasher_HashAndSalt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HashAndSalt'
type PasswordHasher_HashAndSalt_Call struct {
	*mock.Call
}

// HashAndSalt is a helper method to define mock.On call
//   - password string
func (_e *PasswordHasher_Expecter) HashAndSalt(password any) *PasswordHasher_HashAndSalt_Call {
	return &PasswordHasher_HashAndSalt_Call{Call: _e.mock.On("HashAndSalt", password)}
}

func (_c *PasswordHasher_HashAndSalt_Call) Run(run func(password string)) *PasswordHasher_HashAndSalt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *PasswordHasher_HashAndSalt_Call) Return(s string, err error) *PasswordHasher_HashAndSalt_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *PasswordHasher_HashAndSalt_Call) RunAndReturn(run func(password string) (string, error)) *PasswordHasher_HashAndSalt_Call {
	_c.Call.Return(run)
	return _c
}

// VerifyPassword provides a mock function for the type PasswordHasher
func (_mock *PasswordHasher) VerifyPassword(passwordHash string, password string) error {
	ret := _mock.Called(passwordHash, password)

	if len(ret) == 0 {
		panic("no return value specified for VerifyPassword")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = returnFunc(passwordHash, password)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// PasswordHasher_VerifyPassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VerifyPassword'
type PasswordHasher_VerifyPassword_Call struct {
	*mock.Call
}

// VerifyPassword is a helper method to define mock.On call
//   - passwordHash string
//   - password string
func (_e *PasswordHasher_Expecter) VerifyPassword(passwordHash any, password any) *PasswordHasher_VerifyPassword_Call {
	return &PasswordHasher_VerifyPassword_Call{Call: _e.mock.On("VerifyPassword", passwordHash, password)}
}

func (_c *PasswordHasher_VerifyPassword_Call) Run(run func(passwordHash string, password string)) *PasswordHasher_VerifyPassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *PasswordHasher_VerifyPassword_Call) Return(err error) *PasswordHasher_VerifyPassword_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *PasswordHasher_VerifyPassword_Call) RunAndReturn(run func(passwordHash string, password string) error) *PasswordHasher_VerifyPassword_Call {
	_c.Call.Return(run)
	return _c
}
