// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"net/http"

	"github.com/gorilla/sessions"
	mock "github.com/stretchr/testify/mock"
)

// NewSessionRepository creates a new instance of SessionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSessionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *SessionRepository {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &SessionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// SessionRepository is an autogenerated mock type for the SessionRepository type
type SessionRepository struct {
	mock.Mock
}

type SessionRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *SessionRepository) EXPECT() *SessionRepository_Expecter {
	return &SessionRepository_Expecter{mock: &_m.Mock}
}

// AllSessions provides a mock function for the type SessionRepository
func (_mock *SessionRepository) AllSessions(ctx context.Context, name string, offset int, limit int) ([]*sessions.Session, error) {
	ret := _mock.Called(ctx, name, offset, limit)

	if len(ret) == 0 {
		panic("no return value specified for AllSessions")
	}

	var r0 []*sessions.Session
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int, int) ([]*sessions.Session, error)); ok {
		return returnFunc(ctx, name, offset, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int, int) []*sessions.Session); ok {
		r0 = returnFunc(ctx, name, offset, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*sessions.Session)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, int, int) error); ok {
		r1 = returnFunc(ctx, name, offset, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SessionRepository_AllSessions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AllSessions'
type SessionRepository_AllSessions_Call struct {
	*mock.Call
}

// AllSessions is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - offset int
//   - limit int
func (_e *SessionRepository_Expecter) AllSessions(ctx any, name any, offset any, limit any) *SessionRepository_AllSessions_Call {
	return &SessionRepository_AllSessions_Call{Call: _e.mock.On("AllSessions", ctx, name, offset, limit)}
}

func (_c *SessionRepository_AllSessions_Call) Run(run func(ctx context.Context, name string, offset int, limit int)) *SessionRepository_AllSessions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *SessionRepository_AllSessions_Call) Return(sessions1 []*sessions.Session, err error) *SessionRepository_AllSessions_Call {
	_c.Call.Return(sessions1, err)
	return _c
}

func (_c *SessionRepository_AllSessions_Call) RunAndReturn(run func(ctx context.Context, name string, offset int, limit int) ([]*sessions.Session, error)) *SessionRepository_AllSessions_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type SessionRepository
func (_mock *SessionRepository) Get(r *http.Request, name string) (*sessions.Session, error) {
	ret := _mock.Called(r, name)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *sessions.Session
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*http.Request, string) (*sessions.Session, error)); ok {
		return returnFunc(r, name)
	}
	if returnFunc, ok := ret.Get(0).(func(*http.Request, string) *sessions.Session); ok {
		r0 = returnFunc(r, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sessions.Session)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*http.Request, string) error); ok {
		r1 = returnFunc(r, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SessionRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type SessionRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - r *http.Request
//   - name string
func (_e *SessionRepository_Expecter) Get(r any, name any) *SessionRepository_Get_Call {
	return &SessionRepository_Get_Call{Call: _e.mock.On("Get", r, name)}
}

func (_c *SessionRepository_Get_Call) Run(run func(r *http.Request, name string)) *SessionRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *http.Request
		if args[0] != nil {
			arg0 = args[0].(*http.Request)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *SessionRepository_Get_Call) Return(session *sessions.Session, err error) *SessionRepository_Get_Call {
	_c.Call.Return(session, err)
	return _c
}

func (_c *SessionRepository_Get_Call) RunAndReturn(run func(r *http.Request, name string) (*sessions.Session, error)) *SessionRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// KillSessions provides a mock function for the type SessionRepository
func (_mock *SessionRepository) KillSessions(ctx context.Context, sessionIDs ...string) error {
	var tmpRet mock.Arguments
	if len(sessionIDs) > 0 {
		tmpRet = _mock.Called(ctx, sessionIDs)
	} else {
		tmpRet = _mock.Called(ctx)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for KillSessions")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...string) error); ok {
		r0 = returnFunc(ctx, sessionIDs...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// SessionRepository_KillSessions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'KillSessions'
type SessionRepository_KillSessions_Call struct {
	*mock.Call
}

// KillSessions is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionIDs ...string
func (_e *SessionRepository_Expecter) KillSessions(ctx any, sessionIDs ...any) *SessionRepository_KillSessions_Call {
	return &SessionRepository_KillSessions_Call{Call: _e.mock.On("KillSessions",
		append([]any{ctx}, sessionIDs...)...)}
}

func (_c *SessionRepository_KillSessions_Call) Run(run func(ctx context.Context, sessionIDs ...string)) *SessionRepository_KillSessions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		var variadicArgs []string
		if len(args) > 1 {
			variadicArgs = args[1].([]string)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *SessionRepository_KillSessions_Call) Return(err error) *SessionRepository_KillSessions_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *SessionRepository_KillSessions_Call) RunAndReturn(run func(ctx context.Context, sessionIDs ...string) error) *SessionRepository_KillSessions_Call {
	_c.Call.Return(run)
	return _c
}

// KillUserSessions provides a mock function for the type SessionRepository
func (_mock *SessionRepository) KillUserSessions(ctx context.Context, userID string) error {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for KillUserSessions")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// SessionRepository_KillUserSessions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'KillUserSessions'
type SessionRepository_KillUserSessions_Call struct {
	*mock.Call
}

// KillUserSessions is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *SessionRepository_Expecter) KillUserSessions(ctx any, userID any) *SessionRepository_KillUserSessions_Call {
	return &SessionRepository_KillUserSessions_Call{Call: _e.mock.On("KillUserSessions", ctx, userID)}
}

func (_c *SessionRepository_KillUserSessions_Call) Run(run func(ctx context.Context, userID string)) *SessionRepository_KillUserSessions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *SessionRepository_KillUserSessions_Call) Return(err error) *SessionRepository_KillUserSessions_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *SessionRepository_KillUserSessions_Call) RunAndReturn(run func(ctx context.Context, userID string) error) *SessionRepository_KillUserSessions_Call {
	_c.Call.Return(run)
	return _c
}

// New provides a mock function for the type SessionRepository
func (_mock *SessionRepository) New(r *http.Request, name string) (*sessions.Session, error) {
	ret := _mock.Called(r, name)

	if len(ret) == 0 {
		panic("no return value specified for New")
	}

	var r0 *sessions.Session
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*http.Request, string) (*sessions.Session, error)); ok {
		return returnFunc(r, name)
	}
	if returnFunc, ok := ret.Get(0).(func(*http.Request, string) *sessions.Session); ok {
		r0 = returnFunc(r, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sessions.Session)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*http.Request, string) error); ok {
		r1 = returnFunc(r, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SessionRepository_New_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'New'
type SessionRepository_New_Call struct {
	*mock.Call
}

// New is a helper method to define mock.On call
//   - r *http.Request
//   - name string
func (_e *SessionRepository_Expecter) New(r any, name any) *SessionRepository_New_Call {
	return &SessionRepository_New_Call{Call: _e.mock.On("New", r, name)}
}

func (_c *SessionRepository_New_Call) Run(run func(r *http.Request, name string)) *SessionRepository_New_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *http.Request
		if args[0] != nil {
			arg0 = args[0].(*http.Request)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *SessionRepository_New_Call) Return(session *sessions.Session, err error) *SessionRepository_New_Call {
	_c.Call.Return(session, err)
	return _c
}

func (_c *SessionRepository_New_Call) RunAndReturn(run func(r *http.Request, name string) (*sessions.Session, error)) *SessionRepository_New_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type SessionRepository
func (_mock *SessionRepository) Save(r *http.Request, w http.ResponseWriter, s *sessions.Session) error {
	ret := _mock.Called(r, w, s)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*http.Request, http.ResponseWriter, *sessions.Session) error); ok {
		r0 = returnFunc(r, w, s)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// SessionRepository_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type SessionRepository_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - r *http.Request
//   - w http.ResponseWriter
//   - s *sessions.Session
func (_e *SessionRepository_Expecter) Save(r any, w any, s any) *SessionRepository_Save_Call {
	return &SessionRepository_Save_Call{Call: _e.mock.On("Save", r, w, s)}
}

func (_c *SessionRepository_Save_Call) Run(run func(r *http.Request, w http.ResponseWriter, s *sessions.Session)) *SessionRepository_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *http.Request
		if args[0] != nil {
			arg0 = args[0].(*http.Request)
		}
		var arg1 http.ResponseWriter
		if args[1] != nil {
			arg1 = args[1].(http.ResponseWriter)
		}
		var arg2 *sessions.Session
		if args[2] != nil {
			arg2 = args[2].(*sessions.Session)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *SessionRepository_Save_Call) Return(err error) *SessionRepository_Save_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *SessionRepository_Save_Call) RunAndReturn(run func(r *http.Request, w http.ResponseWriter, s *sessions.Session) error) *SessionRepository_Save_Call {
	_c.Call.Return(run)
	return _c
}

// SessionByIDs provides a mock function for the type SessionRepository
func (_mock *SessionRepository) SessionByIDs(ctx context.Context, name string, ids ...string) ([]*sessions.Session, error) {
	var tmpRet mock.Arguments
	if len(ids) > 0 {
		tmpRet = _mock.Called(ctx, name, ids)
	} else {
		tmpRet = _mock.Called(ctx, name)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for SessionByIDs")
	}

	var r0 []*sessions.Session
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...string) ([]*sessions.Session, error)); ok {
		return returnFunc(ctx, name, ids...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...string) []*sessions.Session); ok {
		r0 = returnFunc(ctx, name, ids...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*sessions.Session)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, ...string) error); ok {
		r1 = returnFunc(ctx, name, ids...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SessionRepository_SessionByIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SessionByIDs'
type SessionRepository_SessionByIDs_Call struct {
	*mock.Call
}

// SessionByIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - ids ...string
func (_e *SessionRepository_Expecter) SessionByIDs(ctx any, name any, ids ...any) *SessionRepository_SessionByIDs_Call {
	return &SessionRepository_SessionByIDs_Call{Call: _e.mock.On("SessionByIDs",
		append([]any{ctx, name}, ids...)...)}
}

func (_c *SessionRepository_SessionByIDs_Call) Run(run func(ctx context.Context, name string, ids ...string)) *SessionRepository_SessionByIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []string
		var variadicArgs []string
		if len(args) > 2 {
			variadicArgs = args[2].([]string)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *SessionRepository_SessionByIDs_Call) Return(sessions1 []*sessions.Session, err error) *SessionRepository_SessionByIDs_Call {
	_c.Call.Return(sessions1, err)
	return _c
}

func (_c *SessionRepository_SessionByIDs_Call) RunAndReturn(run func(ctx context.Context, name string, ids ...string) ([]*sessions.Session, error)) *SessionRepository_SessionByIDs_Call {
	_c.Call.Return(run)
	return _c
}
