// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewIEntityTimeStamp creates a new instance of IEntityTimeStamp. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIEntityTimeStamp(t interface {
	mock.TestingT
	Cleanup(func())
}) *IEntityTimeStamp {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &IEntityTimeStamp{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// IEntityTimeStamp is an autogenerated mock type for the IEntityTimeStamp type
type IEntityTimeStamp struct {
	mock.Mock
}

type IEntityTimeStamp_Expecter struct {
	mock *mock.Mock
}

func (_m *IEntityTimeStamp) EXPECT() *IEntityTimeStamp_Expecter {
	return &IEntityTimeStamp_Expecter{mock: &_m.Mock}
}

// SetCreateFields provides a mock function for the type IEntityTimeStamp
func (_mock *IEntityTimeStamp) SetCreateFields(createTime time.Time, createUserID interface{}) {
	_mock.Called(createTime, createUserID)
	return
}

// IEntityTimeStamp_SetCreateFields_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetCreateFields'
type IEntityTimeStamp_SetCreateFields_Call struct {
	*mock.Call
}

// SetCreateFields is a helper method to define mock.On call
//   - createTime time.Time
//   - createUserID interface{}
func (_e *IEntityTimeStamp_Expecter) SetCreateFields(createTime any, createUserID any) *IEntityTimeStamp_SetCreateFields_Call {
	return &IEntityTimeStamp_SetCreateFields_Call{Call: _e.mock.On("SetCreateFields", createTime, createUserID)}
}

func (_c *IEntityTimeStamp_SetCreateFields_Call) Run(run func(createTime time.Time, createUserID interface{})) *IEntityTimeStamp_SetCreateFields_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 time.Time
		if args[0] != nil {
			arg0 = args[0].(time.Time)
		}
		var arg1 interface{}
		if args[1] != nil {
			arg1 = args[1].(interface{})
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *IEntityTimeStamp_SetCreateFields_Call) Return() *IEntityTimeStamp_SetCreateFields_Call {
	_c.Call.Return()
	return _c
}

func (_c *IEntityTimeStamp_SetCreateFields_Call) RunAndReturn(run func(createTime time.Time, createUserID interface{})) *IEntityTimeStamp_SetCreateFields_Call {
	_c.Run(run)
	return _c
}

// SetUpdateFields provides a mock function for the type IEntityTimeStamp
func (_mock *IEntityTimeStamp) SetUpdateFields(cupdateTime time.Time, updateUserID interface{}) {
	_mock.Called(cupdateTime, updateUserID)
	return
}

// IEntityTimeStamp_SetUpdateFields_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetUpdateFields'
type IEntityTimeStamp_SetUpdateFields_Call struct {
	*mock.Call
}

// SetUpdateFields is a helper method to define mock.On call
//   - cupdateTime time.Time
//   - updateUserID interface{}
func (_e *IEntityTimeStamp_Expecter) SetUpdateFields(cupdateTime any, updateUserID any) *IEntityTimeStamp_SetUpdateFields_Call {
	return &IEntityTimeStamp_SetUpdateFields_Call{Call: _e.mock.On("SetUpdateFields", cupdateTime, updateUserID)}
}

func (_c *IEntityTimeStamp_SetUpdateFields_Call) Run(run func(cupdateTime time.Time, updateUserID interface{})) *IEntityTimeStamp_SetUpdateFields_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 time.Time
		if args[0] != nil {
			arg0 = args[0].(time.Time)
		}
		var arg1 interface{}
		if args[1] != nil {
			arg1 = args[1].(interface{})
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *IEntityTimeStamp_SetUpdateFields_Call) Return() *IEntityTimeStamp_SetUpdateFields_Call {
	_c.Call.Return()
	return _c
}

func (_c *IEntityTimeStamp_SetUpdateFields_Call) RunAndReturn(run func(cupdateTime time.Time, updateUserID interface{})) *IEntityTimeStamp_SetUpdateFields_Call {
	_c.Run(run)
	return _c
}
