// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mongo0 "github.com/bldsoft/gost/mongo"
	mock "github.com/stretchr/testify/mock"
	"go.mongodb.org/mongo-driver/v2/mongo"
)

// NewIWatcher creates a new instance of IWatcher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIWatcher(t interface {
	mock.TestingT
	Cleanup(func())
}) *IWatcher {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &IWatcher{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// IWatcher is an autogenerated mock type for the IWatcher type
type IWatcher struct {
	mock.Mock
}

type IWatcher_Expecter struct {
	mock *mock.Mock
}

func (_m *IWatcher) EXPECT() *IWatcher_Expecter {
	return &IWatcher_Expecter{mock: &_m.Mock}
}

// watch provides a mock function for the type IWatcher
func (_mock *IWatcher) watch(ctx context.Context, collection *mongo.Collection, handler mongo0.WatchHandler) {
	_mock.Called(ctx, collection, handler)
	return
}

// IWatcher_watch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'watch'
type IWatcher_watch_Call struct {
	*mock.Call
}

// watch is a helper method to define mock.On call
//   - ctx context.Context
//   - collection *mongo.Collection
//   - handler mongo0.WatchHandler
func (_e *IWatcher_Expecter) watch(ctx any, collection any, handler any) *IWatcher_watch_Call {
	return &IWatcher_watch_Call{Call: _e.mock.On("watch", ctx, collection, handler)}
}

func (_c *IWatcher_watch_Call) Run(run func(ctx context.Context, collection *mongo.Collection, handler mongo0.WatchHandler)) *IWatcher_watch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *mongo.Collection
		if args[1] != nil {
			arg1 = args[1].(*mongo.Collection)
		}
		var arg2 mongo0.WatchHandler
		if args[2] != nil {
			arg2 = args[2].(mongo0.WatchHandler)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *IWatcher_watch_Call) Return() *IWatcher_watch_Call {
	_c.Call.Return()
	return _c
}

func (_c *IWatcher_watch_Call) RunAndReturn(run func(ctx context.Context, collection *mongo.Collection, handler mongo0.WatchHandler)) *IWatcher_watch_Call {
	_c.Run(run)
	return _c
}
