// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/bldsoft/gost/repository"
	mock "github.com/stretchr/testify/mock"
	"go.mongodb.org/mongo-driver/v2/mongo"
)

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepository[T any, U repository.IEntityIDPtr[T]](t interface {
	mock.TestingT
	Cleanup(func())
}) *Repository[T, U] {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &Repository[T, U]{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// Repository is an autogenerated mock type for the Repository type
type Repository[T any, U repository.IEntityIDPtr[T]] struct {
	mock.Mock
}

type Repository_Expecter[T any, U repository.IEntityIDPtr[T]] struct {
	mock *mock.Mock
}

func (_m *Repository[T, U]) EXPECT() *Repository_Expecter[T, U] {
	return &Repository_Expecter[T, U]{mock: &_m.Mock}
}

// AggregateOne provides a mock function for the type Repository
func (_mock *Repository[T, U]) AggregateOne(ctx context.Context, pipeline mongo.Pipeline, entity interface{}) error {
	ret := _mock.Called(ctx, pipeline, entity)

	if len(ret) == 0 {
		panic("no return value specified for AggregateOne")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, mongo.Pipeline, interface{}) error); ok {
		r0 = returnFunc(ctx, pipeline, entity)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Repository_AggregateOne_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AggregateOne'
type Repository_AggregateOne_Call[T any, U repository.IEntityIDPtr[T]] struct {
	*mock.Call
}

// AggregateOne is a helper method to define mock.On call
//   - ctx context.Context
//   - pipeline mongo.Pipeline
//   - entity interface{}
func (_e *Repository_Expecter[T, U]) AggregateOne(ctx any, pipeline any, entity any) *Repository_AggregateOne_Call[T, U] {
	return &Repository_AggregateOne_Call[T, U]{Call: _e.mock.On("AggregateOne", ctx, pipeline, entity)}
}

func (_c *Repository_AggregateOne_Call[T, U]) Run(run func(ctx context.Context, pipeline mongo.Pipeline, entity interface{})) *Repository_AggregateOne_Call[T, U] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 mongo.Pipeline
		if args[1] != nil {
			arg1 = args[1].(mongo.Pipeline)
		}
		var arg2 interface{}
		if args[2] != nil {
			arg2 = args[2].(interface{})
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Repository_AggregateOne_Call[T, U]) Return(err error) *Repository_AggregateOne_Call[T, U] {
	_c.Call.Return(err)
	return _c
}

func (_c *Repository_AggregateOne_Call[T, U]) RunAndReturn(run func(ctx context.Context, pipeline mongo.Pipeline, entity interface{}) error) *Repository_AggregateOne_Call[T, U] {
	_c.Call.Return(run)
	return _c
}

// Collection provides a mock function for the type Repository
func (_mock *Repository[T, U]) Collection() *mongo.Collection {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Collection")
	}

	var r0 *mongo.Collection
	if returnFunc, ok := ret.Get(0).(func() *mongo.Collection); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*mongo.Collection)
		}
	}
	return r0
}

// Repository_Collection_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Collection'
type Repository_Collection_Call[T any, U repository.IEntityIDPtr[T]] struct {
	*mock.Call
}

// Collection is a helper method to define mock.On call
func (_e *Repository_Expecter[T, U]) Collection() *Repository_Collection_Call[T, U] {
	return &Repository_Collection_Call[T, U]{Call: _e.mock.On("Collection")}
}

func (_c *Repository_Collection_Call[T, U]) Run(run func()) *Repository_Collection_Call[T, U] {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Repository_Collection_Call[T, U]) Return(collection *mongo.Collection) *Repository_Collection_Call[T, U] {
	_c.Call.Return(collection)
	return _c
}

func (_c *Repository_Collection_Call[T, U]) RunAndReturn(run func() *mongo.Collection) *Repository_Collection_Call[T, U] {
	_c.Call.Return(run)
	return _c
}

// Count provides a mock function for the type Repository
func (_mock *Repository[T, U]) Count(ctx context.Context, filter interface{}, opt ...*repository.QueryOptions) (int64, error) {
	var tmpRet mock.Arguments
	if len(opt) > 0 {
		tmpRet = _mock.Called(ctx, filter, opt)
	} else {
		tmpRet = _mock.Called(ctx, filter)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Count")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, interface{}, ...*repository.QueryOptions) (int64, error)); ok {
		return returnFunc(ctx, filter, opt...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, interface{}, ...*repository.QueryOptions) int64); ok {
		r0 = returnFunc(ctx, filter, opt...)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, interface{}, ...*repository.QueryOptions) error); ok {
		r1 = returnFunc(ctx, filter, opt...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Repository_Count_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Count'
type Repository_Count_Call[T any, U repository.IEntityIDPtr[T]] struct {
	*mock.Call
}

// Count is a helper method to define mock.On call
//   - ctx context.Context
//   - filter interface{}
//   - opt ...*repository.QueryOptions
func (_e *Repository_Expecter[T, U]) Count(ctx any, filter any, opt ...any) *Repository_Count_Call[T, U] {
	return &Repository_Count_Call[T, U]{Call: _e.mock.On("Count",
		append([]any{ctx, filter}, opt...)...)}
}

func (_c *Repository_Count_Call[T, U]) Run(run func(ctx context.Context, filter interface{}, opt ...*repository.QueryOptions)) *Repository_Count_Call[T, U] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 interface{}
		if args[1] != nil {
			arg1 = args[1].(interface{})
		}
		var arg2 []*repository.QueryOptions
		var variadicArgs []*repository.QueryOptions
		if len(args) > 2 {
			variadicArgs = args[2].([]*repository.QueryOptions)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *Repository_Count_Call[T, U]) Return(n int64, err error) *Repository_Count_Call[T, U] {
	_c.Call.Return(n, err)
	return _c
}

func (_c *Repository_Count_Call[T, U]) RunAndReturn(run func(ctx context.Context, filter interface{}, opt ...*repository.QueryOptions) (int64, error)) *Repository_Count_Call[T, U] {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type Repository
func (_mock *Repository[T, U]) Delete(ctx context.Context, id interface{}, options ...*repository.QueryOptions) error {
	var tmpRet mock.Arguments
	if len(options) > 0 {
		tmpRet = _mock.Called(ctx, id, options)
	} else {
		tmpRet = _mock.Called(ctx, id)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, interface{}, ...*repository.QueryOptions) error); ok {
		r0 = returnFunc(ctx, id, options...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Repository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type Repository_Delete_Call[T any, U repository.IEntityIDPtr[T]] struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id interface{}
//   - options ...*repository.QueryOptions
func (_e *Repository_Expecter[T, U]) Delete(ctx any, id any, options ...any) *Repository_Delete_Call[T, U] {
	return &Repository_Delete_Call[T, U]{Call: _e.mock.On("Delete",
		append([]any{ctx, id}, options...)...)}
}

func (_c *Repository_Delete_Call[T, U]) Run(run func(ctx context.Context, id interface{}, options ...*repository.QueryOptions)) *Repository_Delete_Call[T, U] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 interface{}
		if args[1] != nil {
			arg1 = args[1].(interface{})
		}
		var arg2 []*repository.QueryOptions
		var variadicArgs []*repository.QueryOptions
		if len(args) > 2 {
			variadicArgs = args[2].([]*repository.QueryOptions)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *Repository_Delete_Call[T, U]) Return(err error) *Repository_Delete_Call[T, U] {
	_c.Call.Return(err)
	return _c
}

func (_c *Repository_Delete_Call[T, U]) RunAndReturn(run func(ctx context.Context, id interface{}, options ...*repository.QueryOptions) error) *Repository_Delete_Call[T, U] {
	_c.Call.Return(run)
	return _c
}

// DeleteMany provides a mock function for the type Repository
func (_mock *Repository[T, U]) DeleteMany(ctx context.Context, filter interface{}, options ...*repository.QueryOptions) error {
	var tmpRet mock.Arguments
	if len(options) > 0 {
		tmpRet = _mock.Called(ctx, filter, options)
	} else {
		tmpRet = _mock.Called(ctx, filter)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for DeleteMany")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, interface{}, ...*repository.QueryOptions) error); ok {
		r0 = returnFunc(ctx, filter, options...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Repository_DeleteMany_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteMany'
type Repository_DeleteMany_Call[T any, U repository.IEntityIDPtr[T]] struct {
	*mock.Call
}

// DeleteMany is a helper method to define mock.On call
//   - ctx context.Context
//   - filter interface{}
//   - options ...*repository.QueryOptions
func (_e *Repository_Expecter[T, U]) DeleteMany(ctx any, filter any, options ...any) *Repository_DeleteMany_Call[T, U] {
	return &Repository_DeleteMany_Call[T, U]{Call: _e.mock.On("DeleteMany",
		append([]any{ctx, filter}, options...)...)}
}

func (_c *Repository_DeleteMany_Call[T, U]) Run(run func(ctx context.Context, filter interface{}, options ...*repository.QueryOptions)) *Repository_DeleteMany_Call[T, U] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 interface{}
		if args[1] != nil {
			arg1 = args[1].(interface{})
		}
		var arg2 []*repository.QueryOptions
		var variadicArgs []*repository.QueryOptions
		if len(args) > 2 {
			variadicArgs = args[2].([]*repository.QueryOptions)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *Repository_DeleteMany_Call[T, U]) Return(err error) *Repository_DeleteMany_Call[T, U] {
	_c.Call.Return(err)
	return _c
}

func (_c *Repository_DeleteMany_Call[T, U]) RunAndReturn(run func(ctx context.Context, filter interface{}, options ...*repository.QueryOptions) error) *Repository_DeleteMany_Call[T, U] {
	_c.Call.Return(run)
	return _c
}

// Find provides a mock function for the type Repository
func (_mock *Repository[T, U]) Find(ctx context.Context, filter interface{}, opt ...*repository.QueryOptions) ([]U, error) {
	var tmpRet mock.Arguments
	if len(opt) > 0 {
		tmpRet = _mock.Called(ctx, filter, opt)
	} else {
		tmpRet = _mock.Called(ctx, filter)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Find")
	}

	var r0 []U
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, interface{}, ...*repository.QueryOptions) ([]U, error)); ok {
		return returnFunc(ctx, filter, opt...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, interface{}, ...*repository.QueryOptions) []U); ok {
		r0 = returnFunc(ctx, filter, opt...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]U)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, interface{}, ...*repository.QueryOptions) error); ok {
		r1 = returnFunc(ctx, filter, opt...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Repository_Find_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Find'
type Repository_Find_Call[T any, U repository.IEntityIDPtr[T]] struct {
	*mock.Call
}

// Find is a helper method to define mock.On call
//   - ctx context.Context
//   - filter interface{}
//   - opt ...*repository.QueryOptions
func (_e *Repository_Expecter[T, U]) Find(ctx any, filter any, opt ...any) *Repository_Find_Call[T, U] {
	return &Repository_Find_Call[T, U]{Call: _e.mock.On("Find",
		append([]any{ctx, filter}, opt...)...)}
}

func (_c *Repository_Find_Call[T, U]) Run(run func(ctx context.Context, filter interface{}, opt ...*repository.QueryOptions)) *Repository_Find_Call[T, U] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 interface{}
		if args[1] != nil {
			arg1 = args[1].(interface{})
		}
		var arg2 []*repository.QueryOptions
		var variadicArgs []*repository.QueryOptions
		if len(args) > 2 {
			variadicArgs = args[2].([]*repository.QueryOptions)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *Repository_Find_Call[T, U]) Return(vs []U, err error) *Repository_Find_Call[T, U] {
	_c.Call.Return(vs, err)
	return _c
}

func (_c *Repository_Find_Call[T, U]) RunAndReturn(run func(ctx context.Context, filter interface{}, opt ...*repository.QueryOptions) ([]U, error)) *Repository_Find_Call[T, U] {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function for the type Repository
func (_mock *Repository[T, U]) FindByID(ctx context.Context, id interface{}, options ...*repository.QueryOptions) (U, error) {
	var tmpRet mock.Arguments
	if len(options) > 0 {
		tmpRet = _mock.Called(ctx, id, options)
	} else {
		tmpRet = _mock.Called(ctx, id)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 U
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, interface{}, ...*repository.QueryOptions) (U, error)); ok {
		return returnFunc(ctx, id, options...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, interface{}, ...*repository.QueryOptions) U); ok {
		r0 = returnFunc(ctx, id, options...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(U)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, interface{}, ...*repository.QueryOptions) error); ok {
		r1 = returnFunc(ctx, id, options...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Repository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type Repository_FindByID_Call[T any, U repository.IEntityIDPtr[T]] struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id interface{}
//   - options ...*repository.QueryOptions
func (_e *Repository_Expecter[T, U]) FindByID(ctx any, id any, options ...any) *Repository_FindByID_Call[T, U] {
	return &Repository_FindByID_Call[T, U]{Call: _e.mock.On("FindByID",
		append([]any{ctx, id}, options...)...)}
}

func (_c *Repository_FindByID_Call[T, U]) Run(run func(ctx context.Context, id interface{}, options ...*repository.QueryOptions)) *Repository_FindByID_Call[T, U] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 interface{}
		if args[1] != nil {
			arg1 = args[1].(interface{})
		}
		var arg2 []*repository.QueryOptions
		var variadicArgs []*repository.QueryOptions
		if len(args) > 2 {
			variadicArgs = args[2].([]*repository.QueryOptions)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *Repository_FindByID_Call[T, U]) Return(v U, err error) *Repository_FindByID_Call[T, U] {
	_c.Call.Return(v, err)
	return _c
}

func (_c *Repository_FindByID_Call[T, U]) RunAndReturn(run func(ctx context.Context, id interface{}, options ...*repository.QueryOptions) (U, error)) *Repository_FindByID_Call[T, U] {
	_c.Call.Return(run)
	return _c
}

// FindByIDs provides a mock function for the type Repository
func (_mock *Repository[T, U]) FindByIDs(ctx context.Context, ids []interface{}, preserveOrder bool, options ...*repository.QueryOptions) ([]U, error) {
	var tmpRet mock.Arguments
	if len(options) > 0 {
		tmpRet = _mock.Called(ctx, ids, preserveOrder, options)
	} else {
		tmpRet = _mock.Called(ctx, ids, preserveOrder)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for FindByIDs")
	}

	var r0 []U
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []interface{}, bool, ...*repository.QueryOptions) ([]U, error)); ok {
		return returnFunc(ctx, ids, preserveOrder, options...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []interface{}, bool, ...*repository.QueryOptions) []U); ok {
		r0 = returnFunc(ctx, ids, preserveOrder, options...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]U)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []interface{}, bool, ...*repository.QueryOptions) error); ok {
		r1 = returnFunc(ctx, ids, preserveOrder, options...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Repository_FindByIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByIDs'
type Repository_FindByIDs_Call[T any, U repository.IEntityIDPtr[T]] struct {
	*mock.Call
}

// FindByIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - ids []interface{}
//   - preserveOrder bool
//   - options ...*repository.QueryOptions
func (_e *Repository_Expecter[T, U]) FindByIDs(ctx any, ids any, preserveOrder any, options ...any) *Repository_FindByIDs_Call[T, U] {
	return &Repository_FindByIDs_Call[T, U]{Call: _e.mock.On("FindByIDs",
		append([]any{ctx, ids, preserveOrder}, options...)...)}
}

func (_c *Repository_FindByIDs_Call[T, U]) Run(run func(ctx context.Context, ids []interface{}, preserveOrder bool, options ...*repository.QueryOptions)) *Repository_FindByIDs_Call[T, U] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []interface{}
		if args[1] != nil {
			arg1 = args[1].([]interface{})
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		var arg3 []*repository.QueryOptions
		var variadicArgs []*repository.QueryOptions
		if len(args) > 3 {
			variadicArgs = args[3].([]*repository.QueryOptions)
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *Repository_FindByIDs_Call[T, U]) Return(vs []U, err error) *Repository_FindByIDs_Call[T, U] {
	_c.Call.Return(vs, err)
	return _c
}

func (_c *Repository_FindByIDs_Call[T, U]) RunAndReturn(run func(ctx context.Context, ids []interface{}, preserveOrder bool, options ...*repository.QueryOptions) ([]U, error)) *Repository_FindByIDs_Call[T, U] {
	_c.Call.Return(run)
	return _c
}

// FindByStringIDs provides a mock function for the type Repository
func (_mock *Repository[T, U]) FindByStringIDs(ctx context.Context, ids []string, preserveOrder bool, options ...*repository.QueryOptions) ([]U, error) {
	var tmpRet mock.Arguments
	if len(options) > 0 {
		tmpRet = _mock.Called(ctx, ids, preserveOrder, options)
	} else {
		tmpRet = _mock.Called(ctx, ids, preserveOrder)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for FindByStringIDs")
	}

	var r0 []U
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string, bool, ...*repository.QueryOptions) ([]U, error)); ok {
		return returnFunc(ctx, ids, preserveOrder, options...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string, bool, ...*repository.QueryOptions) []U); ok {
		r0 = returnFunc(ctx, ids, preserveOrder, options...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]U)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []string, bool, ...*repository.QueryOptions) error); ok {
		r1 = returnFunc(ctx, ids, preserveOrder, options...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Repository_FindByStringIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByStringIDs'
type Repository_FindByStringIDs_Call[T any, U repository.IEntityIDPtr[T]] struct {
	*mock.Call
}

// FindByStringIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - ids []string
//   - preserveOrder bool
//   - options ...*repository.QueryOptions
func (_e *Repository_Expecter[T, U]) FindByStringIDs(ctx any, ids any, preserveOrder any, options ...any) *Repository_FindByStringIDs_Call[T, U] {
	return &Repository_FindByStringIDs_Call[T, U]{Call: _e.mock.On("FindByStringIDs",
		append([]any{ctx, ids, preserveOrder}, options...)...)}
}

func (_c *Repository_FindByStringIDs_Call[T, U]) Run(run func(ctx context.Context, ids []string, preserveOrder bool, options ...*repository.QueryOptions)) *Repository_FindByStringIDs_Call[T, U] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		if args[1] != nil {
			arg1 = args[1].([]string)
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		var arg3 []*repository.QueryOptions
		var variadicArgs []*repository.QueryOptions
		if len(args) > 3 {
			variadicArgs = args[3].([]*repository.QueryOptions)
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *Repository_FindByStringIDs_Call[T, U]) Return(vs []U, err error) *Repository_FindByStringIDs_Call[T, U] {
	_c.Call.Return(vs, err)
	return _c
}

func (_c *Repository_FindByStringIDs_Call[T, U]) RunAndReturn(run func(ctx context.Context, ids []string, preserveOrder bool, options ...*repository.QueryOptions) ([]U, error)) *Repository_FindByStringIDs_Call[T, U] {
	_c.Call.Return(run)
	return _c
}

// FindOne provides a mock function for the type Repository
func (_mock *Repository[T, U]) FindOne(ctx context.Context, filter interface{}, opts ...*repository.QueryOptions) (U, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, filter, opts)
	} else {
		tmpRet = _mock.Called(ctx, filter)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for FindOne")
	}

	var r0 U
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, interface{}, ...*repository.QueryOptions) (U, error)); ok {
		return returnFunc(ctx, filter, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, interface{}, ...*repository.QueryOptions) U); ok {
		r0 = returnFunc(ctx, filter, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(U)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, interface{}, ...*repository.QueryOptions) error); ok {
		r1 = returnFunc(ctx, filter, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Repository_FindOne_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindOne'
type Repository_FindOne_Call[T any, U repository.IEntityIDPtr[T]] struct {
	*mock.Call
}

// FindOne is a helper method to define mock.On call
//   - ctx context.Context
//   - filter interface{}
//   - opts ...*repository.QueryOptions
func (_e *Repository_Expecter[T, U]) FindOne(ctx any, filter any, opts ...any) *Repository_FindOne_Call[T, U] {
	return &Repository_FindOne_Call[T, U]{Call: _e.mock.On("FindOne",
		append([]any{ctx, filter}, opts...)...)}
}

func (_c *Repository_FindOne_Call[T, U]) Run(run func(ctx context.Context, filter interface{}, opts ...*repository.QueryOptions)) *Repository_FindOne_Call[T, U] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 interface{}
		if args[1] != nil {
			arg1 = args[1].(interface{})
		}
		var arg2 []*repository.QueryOptions
		var variadicArgs []*repository.QueryOptions
		if len(args) > 2 {
			variadicArgs = args[2].([]*repository.QueryOptions)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *Repository_FindOne_Call[T, U]) Return(v U, err error) *Repository_FindOne_Call[T, U] {
	_c.Call.Return(v, err)
	return _c
}

func (_c *Repository_FindOne_Call[T, U]) RunAndReturn(run func(ctx context.Context, filter interface{}, opts ...*repository.QueryOptions) (U, error)) *Repository_FindOne_Call[T, U] {
	_c.Call.Return(run)
	return _c
}

// FindOneAndDelete provides a mock function for the type Repository
func (_mock *Repository[T, U]) FindOneAndDelete(ctx context.Context, filter interface{}, opt ...*repository.QueryOptions) (U, error) {
	var tmpRet mock.Arguments
	if len(opt) > 0 {
		tmpRet = _mock.Called(ctx, filter, opt)
	} else {
		tmpRet = _mock.Called(ctx, filter)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for FindOneAndDelete")
	}

	var r0 U
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, interface{}, ...*repository.QueryOptions) (U, error)); ok {
		return returnFunc(ctx, filter, opt...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, interface{}, ...*repository.QueryOptions) U); ok {
		r0 = returnFunc(ctx, filter, opt...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(U)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, interface{}, ...*repository.QueryOptions) error); ok {
		r1 = returnFunc(ctx, filter, opt...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Repository_FindOneAndDelete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindOneAndDelete'
type Repository_FindOneAndDelete_Call[T any, U repository.IEntityIDPtr[T]] struct {
	*mock.Call
}

// FindOneAndDelete is a helper method to define mock.On call
//   - ctx context.Context
//   - filter interface{}
//   - opt ...*repository.QueryOptions
func (_e *Repository_Expecter[T, U]) FindOneAndDelete(ctx any, filter any, opt ...any) *Repository_FindOneAndDelete_Call[T, U] {
	return &Repository_FindOneAndDelete_Call[T, U]{Call: _e.mock.On("FindOneAndDelete",
		append([]any{ctx, filter}, opt...)...)}
}

func (_c *Repository_FindOneAndDelete_Call[T, U]) Run(run func(ctx context.Context, filter interface{}, opt ...*repository.QueryOptions)) *Repository_FindOneAndDelete_Call[T, U] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 interface{}
		if args[1] != nil {
			arg1 = args[1].(interface{})
		}
		var arg2 []*repository.QueryOptions
		var variadicArgs []*repository.QueryOptions
		if len(args) > 2 {
			variadicArgs = args[2].([]*repository.QueryOptions)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *Repository_FindOneAndDelete_Call[T, U]) Return(v U, err error) *Repository_FindOneAndDelete_Call[T, U] {
	_c.Call.Return(v, err)
	return _c
}

func (_c *Repository_FindOneAndDelete_Call[T, U]) RunAndReturn(run func(ctx context.Context, filter interface{}, opt ...*repository.QueryOptions) (U, error)) *Repository_FindOneAndDelete_Call[T, U] {
	_c.Call.Return(run)
	return _c
}

// GetAll provides a mock function for the type Repository
func (_mock *Repository[T, U]) GetAll(ctx context.Context, options ...*repository.QueryOptions) ([]U, error) {
	var tmpRet mock.Arguments
	if len(options) > 0 {
		tmpRet = _mock.Called(ctx, options)
	} else {
		tmpRet = _mock.Called(ctx)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []U
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...*repository.QueryOptions) ([]U, error)); ok {
		return returnFunc(ctx, options...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...*repository.QueryOptions) []U); ok {
		r0 = returnFunc(ctx, options...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]U)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ...*repository.QueryOptions) error); ok {
		r1 = returnFunc(ctx, options...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Repository_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type Repository_GetAll_Call[T any, U repository.IEntityIDPtr[T]] struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
//   - ctx context.Context
//   - options ...*repository.QueryOptions
func (_e *Repository_Expecter[T, U]) GetAll(ctx any, options ...any) *Repository_GetAll_Call[T, U] {
	return &Repository_GetAll_Call[T, U]{Call: _e.mock.On("GetAll",
		append([]any{ctx}, options...)...)}
}

func (_c *Repository_GetAll_Call[T, U]) Run(run func(ctx context.Context, options ...*repository.QueryOptions)) *Repository_GetAll_Call[T, U] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []*repository.QueryOptions
		var variadicArgs []*repository.QueryOptions
		if len(args) > 1 {
			variadicArgs = args[1].([]*repository.QueryOptions)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *Repository_GetAll_Call[T, U]) Return(vs []U, err error) *Repository_GetAll_Call[T, U] {
	_c.Call.Return(vs, err)
	return _c
}

func (_c *Repository_GetAll_Call[T, U]) RunAndReturn(run func(ctx context.Context, options ...*repository.QueryOptions) ([]U, error)) *Repository_GetAll_Call[T, U] {
	_c.Call.Return(run)
	return _c
}

// Insert provides a mock function for the type Repository
func (_mock *Repository[T, U]) Insert(ctx context.Context, entity U) error {
	ret := _mock.Called(ctx, entity)

	if len(ret) == 0 {
		panic("no return value specified for Insert")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, U) error); ok {
		r0 = returnFunc(ctx, entity)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Repository_Insert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Insert'
type Repository_Insert_Call[T any, U repository.IEntityIDPtr[T]] struct {
	*mock.Call
}

// Insert is a helper method to define mock.On call
//   - ctx context.Context
//   - entity U
func (_e *Repository_Expecter[T, U]) Insert(ctx any, entity any) *Repository_Insert_Call[T, U] {
	return &Repository_Insert_Call[T, U]{Call: _e.mock.On("Insert", ctx, entity)}
}

func (_c *Repository_Insert_Call[T, U]) Run(run func(ctx context.Context, entity U)) *Repository_Insert_Call[T, U] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 U
		if args[1] != nil {
			arg1 = args[1].(U)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Repository_Insert_Call[T, U]) Return(err error) *Repository_Insert_Call[T, U] {
	_c.Call.Return(err)
	return _c
}

func (_c *Repository_Insert_Call[T, U]) RunAndReturn(run func(ctx context.Context, entity U) error) *Repository_Insert_Call[T, U] {
	_c.Call.Return(run)
	return _c
}

// InsertMany provides a mock function for the type Repository
func (_mock *Repository[T, U]) InsertMany(ctx context.Context, entities []U) error {
	ret := _mock.Called(ctx, entities)

	if len(ret) == 0 {
		panic("no return value specified for InsertMany")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []U) error); ok {
		r0 = returnFunc(ctx, entities)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Repository_InsertMany_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertMany'
type Repository_InsertMany_Call[T any, U repository.IEntityIDPtr[T]] struct {
	*mock.Call
}

// InsertMany is a helper method to define mock.On call
//   - ctx context.Context
//   - entities []U
func (_e *Repository_Expecter[T, U]) InsertMany(ctx any, entities any) *Repository_InsertMany_Call[T, U] {
	return &Repository_InsertMany_Call[T, U]{Call: _e.mock.On("InsertMany", ctx, entities)}
}

func (_c *Repository_InsertMany_Call[T, U]) Run(run func(ctx context.Context, entities []U)) *Repository_InsertMany_Call[T, U] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []U
		if args[1] != nil {
			arg1 = args[1].([]U)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Repository_InsertMany_Call[T, U]) Return(err error) *Repository_InsertMany_Call[T, U] {
	_c.Call.Return(err)
	return _c
}

func (_c *Repository_InsertMany_Call[T, U]) RunAndReturn(run func(ctx context.Context, entities []U) error) *Repository_InsertMany_Call[T, U] {
	_c.Call.Return(run)
	return _c
}

// InsertOrReplace provides a mock function for the type Repository
func (_mock *Repository[T, U]) InsertOrReplace(ctx context.Context, entity U) (bool, error) {
	ret := _mock.Called(ctx, entity)

	if len(ret) == 0 {
		panic("no return value specified for InsertOrReplace")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, U) (bool, error)); ok {
		return returnFunc(ctx, entity)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, U) bool); ok {
		r0 = returnFunc(ctx, entity)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, U) error); ok {
		r1 = returnFunc(ctx, entity)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Repository_InsertOrReplace_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertOrReplace'
type Repository_InsertOrReplace_Call[T any, U repository.IEntityIDPtr[T]] struct {
	*mock.Call
}

// InsertOrReplace is a helper method to define mock.On call
//   - ctx context.Context
//   - entity U
func (_e *Repository_Expecter[T, U]) InsertOrReplace(ctx any, entity any) *Repository_InsertOrReplace_Call[T, U] {
	return &Repository_InsertOrReplace_Call[T, U]{Call: _e.mock.On("InsertOrReplace", ctx, entity)}
}

func (_c *Repository_InsertOrReplace_Call[T, U]) Run(run func(ctx context.Context, entity U)) *Repository_InsertOrReplace_Call[T, U] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 U
		if args[1] != nil {
			arg1 = args[1].(U)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Repository_InsertOrReplace_Call[T, U]) Return(inserted bool, err error) *Repository_InsertOrReplace_Call[T, U] {
	_c.Call.Return(inserted, err)
	return _c
}

func (_c *Repository_InsertOrReplace_Call[T, U]) RunAndReturn(run func(ctx context.Context, entity U) (bool, error)) *Repository_InsertOrReplace_Call[T, U] {
	_c.Call.Return(run)
	return _c
}

// InsertOrReplaceMany provides a mock function for the type Repository
func (_mock *Repository[T, U]) InsertOrReplaceMany(ctx context.Context, entities []U) error {
	ret := _mock.Called(ctx, entities)

	if len(ret) == 0 {
		panic("no return value specified for InsertOrReplaceMany")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []U) error); ok {
		r0 = returnFunc(ctx, entities)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Repository_InsertOrReplaceMany_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertOrReplaceMany'
type Repository_InsertOrReplaceMany_Call[T any, U repository.IEntityIDPtr[T]] struct {
	*mock.Call
}

// InsertOrReplaceMany is a helper method to define mock.On call
//   - ctx context.Context
//   - entities []U
func (_e *Repository_Expecter[T, U]) InsertOrReplaceMany(ctx any, entities any) *Repository_InsertOrReplaceMany_Call[T, U] {
	return &Repository_InsertOrReplaceMany_Call[T, U]{Call: _e.mock.On("InsertOrReplaceMany", ctx, entities)}
}

func (_c *Repository_InsertOrReplaceMany_Call[T, U]) Run(run func(ctx context.Context, entities []U)) *Repository_InsertOrReplaceMany_Call[T, U] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []U
		if args[1] != nil {
			arg1 = args[1].([]U)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Repository_InsertOrReplaceMany_Call[T, U]) Return(err error) *Repository_InsertOrReplaceMany_Call[T, U] {
	_c.Call.Return(err)
	return _c
}

func (_c *Repository_InsertOrReplaceMany_Call[T, U]) RunAndReturn(run func(ctx context.Context, entities []U) error) *Repository_InsertOrReplaceMany_Call[T, U] {
	_c.Call.Return(run)
	return _c
}

// InsertOrReplaceOne provides a mock function for the type Repository
func (_mock *Repository[T, U]) InsertOrReplaceOne(ctx context.Context, filter any, replacement U, options ...*repository.QueryOptions) (bool, error) {
	var tmpRet mock.Arguments
	if len(options) > 0 {
		tmpRet = _mock.Called(ctx, filter, replacement, options)
	} else {
		tmpRet = _mock.Called(ctx, filter, replacement)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for InsertOrReplaceOne")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, any, U, ...*repository.QueryOptions) (bool, error)); ok {
		return returnFunc(ctx, filter, replacement, options...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, any, U, ...*repository.QueryOptions) bool); ok {
		r0 = returnFunc(ctx, filter, replacement, options...)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, any, U, ...*repository.QueryOptions) error); ok {
		r1 = returnFunc(ctx, filter, replacement, options...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Repository_InsertOrReplaceOne_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertOrReplaceOne'
type Repository_InsertOrReplaceOne_Call[T any, U repository.IEntityIDPtr[T]] struct {
	*mock.Call
}

// InsertOrReplaceOne is a helper method to define mock.On call
//   - ctx context.Context
//   - filter any
//   - replacement U
//   - options ...*repository.QueryOptions
func (_e *Repository_Expecter[T, U]) InsertOrReplaceOne(ctx any, filter any, replacement any, options ...any) *Repository_InsertOrReplaceOne_Call[T, U] {
	return &Repository_InsertOrReplaceOne_Call[T, U]{Call: _e.mock.On("InsertOrReplaceOne",
		append([]any{ctx, filter, replacement}, options...)...)}
}

func (_c *Repository_InsertOrReplaceOne_Call[T, U]) Run(run func(ctx context.Context, filter any, replacement U, options ...*repository.QueryOptions)) *Repository_InsertOrReplaceOne_Call[T, U] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 any
		if args[1] != nil {
			arg1 = args[1].(any)
		}
		var arg2 U
		if args[2] != nil {
			arg2 = args[2].(U)
		}
		var arg3 []*repository.QueryOptions
		var variadicArgs []*repository.QueryOptions
		if len(args) > 3 {
			variadicArgs = args[3].([]*repository.QueryOptions)
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *Repository_InsertOrReplaceOne_Call[T, U]) Return(inserted bool, err error) *Repository_InsertOrReplaceOne_Call[T, U] {
	_c.Call.Return(inserted, err)
	return _c
}

func (_c *Repository_InsertOrReplaceOne_Call[T, U]) RunAndReturn(run func(ctx context.Context, filter any, replacement U, options ...*repository.QueryOptions) (bool, error)) *Repository_InsertOrReplaceOne_Call[T, U] {
	_c.Call.Return(run)
	return _c
}

// Name provides a mock function for the type Repository
func (_mock *Repository[T, U]) Name() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Name")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// Repository_Name_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Name'
type Repository_Name_Call[T any, U repository.IEntityIDPtr[T]] struct {
	*mock.Call
}

// Name is a helper method to define mock.On call
func (_e *Repository_Expecter[T, U]) Name() *Repository_Name_Call[T, U] {
	return &Repository_Name_Call[T, U]{Call: _e.mock.On("Name")}
}

func (_c *Repository_Name_Call[T, U]) Run(run func()) *Repository_Name_Call[T, U] {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Repository_Name_Call[T, U]) Return(s string) *Repository_Name_Call[T, U] {
	_c.Call.Return(s)
	return _c
}

func (_c *Repository_Name_Call[T, U]) RunAndReturn(run func() string) *Repository_Name_Call[T, U] {
	_c.Call.Return(run)
	return _c
}

// Replace provides a mock function for the type Repository
func (_mock *Repository[T, U]) Replace(ctx context.Context, replacement U, options ...*repository.QueryOptions) error {
	var tmpRet mock.Arguments
	if len(options) > 0 {
		tmpRet = _mock.Called(ctx, replacement, options)
	} else {
		tmpRet = _mock.Called(ctx, replacement)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Replace")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, U, ...*repository.QueryOptions) error); ok {
		r0 = returnFunc(ctx, replacement, options...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Repository_Replace_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Replace'
type Repository_Replace_Call[T any, U repository.IEntityIDPtr[T]] struct {
	*mock.Call
}

// Replace is a helper method to define mock.On call
//   - ctx context.Context
//   - replacement U
//   - options ...*repository.QueryOptions
func (_e *Repository_Expecter[T, U]) Replace(ctx any, replacement any, options ...any) *Repository_Replace_Call[T, U] {
	return &Repository_Replace_Call[T, U]{Call: _e.mock.On("Replace",
		append([]any{ctx, replacement}, options...)...)}
}

func (_c *Repository_Replace_Call[T, U]) Run(run func(ctx context.Context, replacement U, options ...*repository.QueryOptions)) *Repository_Replace_Call[T, U] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 U
		if args[1] != nil {
			arg1 = args[1].(U)
		}
		var arg2 []*repository.QueryOptions
		var variadicArgs []*repository.QueryOptions
		if len(args) > 2 {
			variadicArgs = args[2].([]*repository.QueryOptions)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *Repository_Replace_Call[T, U]) Return(err error) *Repository_Replace_Call[T, U] {
	_c.Call.Return(err)
	return _c
}

func (_c *Repository_Replace_Call[T, U]) RunAndReturn(run func(ctx context.Context, replacement U, options ...*repository.QueryOptions) error) *Repository_Replace_Call[T, U] {
	_c.Call.Return(run)
	return _c
}

// ReplaceOne provides a mock function for the type Repository
func (_mock *Repository[T, U]) ReplaceOne(ctx context.Context, filter any, replacement U, options ...*repository.QueryOptions) error {
	var tmpRet mock.Arguments
	if len(options) > 0 {
		tmpRet = _mock.Called(ctx, filter, replacement, options)
	} else {
		tmpRet = _mock.Called(ctx, filter, replacement)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for ReplaceOne")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, any, U, ...*repository.QueryOptions) error); ok {
		r0 = returnFunc(ctx, filter, replacement, options...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Repository_ReplaceOne_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReplaceOne'
type Repository_ReplaceOne_Call[T any, U repository.IEntityIDPtr[T]] struct {
	*mock.Call
}

// ReplaceOne is a helper method to define mock.On call
//   - ctx context.Context
//   - filter any
//   - replacement U
//   - options ...*repository.QueryOptions
func (_e *Repository_Expecter[T, U]) ReplaceOne(ctx any, filter any, replacement any, options ...any) *Repository_ReplaceOne_Call[T, U] {
	return &Repository_ReplaceOne_Call[T, U]{Call: _e.mock.On("ReplaceOne",
		append([]any{ctx, filter, replacement}, options...)...)}
}

func (_c *Repository_ReplaceOne_Call[T, U]) Run(run func(ctx context.Context, filter any, replacement U, options ...*repository.QueryOptions)) *Repository_ReplaceOne_Call[T, U] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 any
		if args[1] != nil {
			arg1 = args[1].(any)
		}
		var arg2 U
		if args[2] != nil {
			arg2 = args[2].(U)
		}
		var arg3 []*repository.QueryOptions
		var variadicArgs []*repository.QueryOptions
		if len(args) > 3 {
			variadicArgs = args[3].([]*repository.QueryOptions)
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *Repository_ReplaceOne_Call[T, U]) Return(err error) *Repository_ReplaceOne_Call[T, U] {
	_c.Call.Return(err)
	return _c
}

func (_c *Repository_ReplaceOne_Call[T, U]) RunAndReturn(run func(ctx context.Context, filter any, replacement U, options ...*repository.QueryOptions) error) *Repository_ReplaceOne_Call[T, U] {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type Repository
func (_mock *Repository[T, U]) Update(ctx context.Context, entity U, options ...*repository.QueryOptions) error {
	var tmpRet mock.Arguments
	if len(options) > 0 {
		tmpRet = _mock.Called(ctx, entity, options)
	} else {
		tmpRet = _mock.Called(ctx, entity)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, U, ...*repository.QueryOptions) error); ok {
		r0 = returnFunc(ctx, entity, options...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Repository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type Repository_Update_Call[T any, U repository.IEntityIDPtr[T]] struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - entity U
//   - options ...*repository.QueryOptions
func (_e *Repository_Expecter[T, U]) Update(ctx any, entity any, options ...any) *Repository_Update_Call[T, U] {
	return &Repository_Update_Call[T, U]{Call: _e.mock.On("Update",
		append([]any{ctx, entity}, options...)...)}
}

func (_c *Repository_Update_Call[T, U]) Run(run func(ctx context.Context, entity U, options ...*repository.QueryOptions)) *Repository_Update_Call[T, U] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 U
		if args[1] != nil {
			arg1 = args[1].(U)
		}
		var arg2 []*repository.QueryOptions
		var variadicArgs []*repository.QueryOptions
		if len(args) > 2 {
			variadicArgs = args[2].([]*repository.QueryOptions)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *Repository_Update_Call[T, U]) Return(err error) *Repository_Update_Call[T, U] {
	_c.Call.Return(err)
	return _c
}

func (_c *Repository_Update_Call[T, U]) RunAndReturn(run func(ctx context.Context, entity U, options ...*repository.QueryOptions) error) *Repository_Update_Call[T, U] {
	_c.Call.Return(run)
	return _c
}

// UpdateAndGetByID provides a mock function for the type Repository
func (_mock *Repository[T, U]) UpdateAndGetByID(ctx context.Context, updateEntity U, returnNewDocument bool, queryOpt ...*repository.QueryOptions) (U, error) {
	var tmpRet mock.Arguments
	if len(queryOpt) > 0 {
		tmpRet = _mock.Called(ctx, updateEntity, returnNewDocument, queryOpt)
	} else {
		tmpRet = _mock.Called(ctx, updateEntity, returnNewDocument)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for UpdateAndGetByID")
	}

	var r0 U
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, U, bool, ...*repository.QueryOptions) (U, error)); ok {
		return returnFunc(ctx, updateEntity, returnNewDocument, queryOpt...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, U, bool, ...*repository.QueryOptions) U); ok {
		r0 = returnFunc(ctx, updateEntity, returnNewDocument, queryOpt...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(U)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, U, bool, ...*repository.QueryOptions) error); ok {
		r1 = returnFunc(ctx, updateEntity, returnNewDocument, queryOpt...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Repository_UpdateAndGetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateAndGetByID'
type Repository_UpdateAndGetByID_Call[T any, U repository.IEntityIDPtr[T]] struct {
	*mock.Call
}

// UpdateAndGetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - updateEntity U
//   - returnNewDocument bool
//   - queryOpt ...*repository.QueryOptions
func (_e *Repository_Expecter[T, U]) UpdateAndGetByID(ctx any, updateEntity any, returnNewDocument any, queryOpt ...any) *Repository_UpdateAndGetByID_Call[T, U] {
	return &Repository_UpdateAndGetByID_Call[T, U]{Call: _e.mock.On("UpdateAndGetByID",
		append([]any{ctx, updateEntity, returnNewDocument}, queryOpt...)...)}
}

func (_c *Repository_UpdateAndGetByID_Call[T, U]) Run(run func(ctx context.Context, updateEntity U, returnNewDocument bool, queryOpt ...*repository.QueryOptions)) *Repository_UpdateAndGetByID_Call[T, U] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 U
		if args[1] != nil {
			arg1 = args[1].(U)
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		var arg3 []*repository.QueryOptions
		var variadicArgs []*repository.QueryOptions
		if len(args) > 3 {
			variadicArgs = args[3].([]*repository.QueryOptions)
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *Repository_UpdateAndGetByID_Call[T, U]) Return(v U, err error) *Repository_UpdateAndGetByID_Call[T, U] {
	_c.Call.Return(v, err)
	return _c
}

func (_c *Repository_UpdateAndGetByID_Call[T, U]) RunAndReturn(run func(ctx context.Context, updateEntity U, returnNewDocument bool, queryOpt ...*repository.QueryOptions) (U, error)) *Repository_UpdateAndGetByID_Call[T, U] {
	_c.Call.Return(run)
	return _c
}

// UpdateMany provides a mock function for the type Repository
func (_mock *Repository[T, U]) UpdateMany(ctx context.Context, entities []U) error {
	ret := _mock.Called(ctx, entities)

	if len(ret) == 0 {
		panic("no return value specified for UpdateMany")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []U) error); ok {
		r0 = returnFunc(ctx, entities)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Repository_UpdateMany_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateMany'
type Repository_UpdateMany_Call[T any, U repository.IEntityIDPtr[T]] struct {
	*mock.Call
}

// UpdateMany is a helper method to define mock.On call
//   - ctx context.Context
//   - entities []U
func (_e *Repository_Expecter[T, U]) UpdateMany(ctx any, entities any) *Repository_UpdateMany_Call[T, U] {
	return &Repository_UpdateMany_Call[T, U]{Call: _e.mock.On("UpdateMany", ctx, entities)}
}

func (_c *Repository_UpdateMany_Call[T, U]) Run(run func(ctx context.Context, entities []U)) *Repository_UpdateMany_Call[T, U] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []U
		if args[1] != nil {
			arg1 = args[1].([]U)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Repository_UpdateMany_Call[T, U]) Return(err error) *Repository_UpdateMany_Call[T, U] {
	_c.Call.Return(err)
	return _c
}

func (_c *Repository_UpdateMany_Call[T, U]) RunAndReturn(run func(ctx context.Context, entities []U) error) *Repository_UpdateMany_Call[T, U] {
	_c.Call.Return(run)
	return _c
}

// UpdateOne provides a mock function for the type Repository
func (_mock *Repository[T, U]) UpdateOne(ctx context.Context, filter interface{}, update interface{}, options ...*repository.QueryOptions) error {
	var tmpRet mock.Arguments
	if len(options) > 0 {
		tmpRet = _mock.Called(ctx, filter, update, options)
	} else {
		tmpRet = _mock.Called(ctx, filter, update)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for UpdateOne")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, interface{}, interface{}, ...*repository.QueryOptions) error); ok {
		r0 = returnFunc(ctx, filter, update, options...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Repository_UpdateOne_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateOne'
type Repository_UpdateOne_Call[T any, U repository.IEntityIDPtr[T]] struct {
	*mock.Call
}

// UpdateOne is a helper method to define mock.On call
//   - ctx context.Context
//   - filter interface{}
//   - update interface{}
//   - options ...*repository.QueryOptions
func (_e *Repository_Expecter[T, U]) UpdateOne(ctx any, filter any, update any, options ...any) *Repository_UpdateOne_Call[T, U] {
	return &Repository_UpdateOne_Call[T, U]{Call: _e.mock.On("UpdateOne",
		append([]any{ctx, filter, update}, options...)...)}
}

func (_c *Repository_UpdateOne_Call[T, U]) Run(run func(ctx context.Context, filter interface{}, update interface{}, options ...*repository.QueryOptions)) *Repository_UpdateOne_Call[T, U] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 interface{}
		if args[1] != nil {
			arg1 = args[1].(interface{})
		}
		var arg2 interface{}
		if args[2] != nil {
			arg2 = args[2].(interface{})
		}
		var arg3 []*repository.QueryOptions
		var variadicArgs []*repository.QueryOptions
		if len(args) > 3 {
			variadicArgs = args[3].([]*repository.QueryOptions)
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *Repository_UpdateOne_Call[T, U]) Return(err error) *Repository_UpdateOne_Call[T, U] {
	_c.Call.Return(err)
	return _c
}

func (_c *Repository_UpdateOne_Call[T, U]) RunAndReturn(run func(ctx context.Context, filter interface{}, update interface{}, options ...*repository.QueryOptions) error) *Repository_UpdateOne_Call[T, U] {
	_c.Call.Return(run)
	return _c
}

// Upsert provides a mock function for the type Repository
func (_mock *Repository[T, U]) Upsert(ctx context.Context, entity U, opt ...*repository.QueryOptions) error {
	var tmpRet mock.Arguments
	if len(opt) > 0 {
		tmpRet = _mock.Called(ctx, entity, opt)
	} else {
		tmpRet = _mock.Called(ctx, entity)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Upsert")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, U, ...*repository.QueryOptions) error); ok {
		r0 = returnFunc(ctx, entity, opt...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Repository_Upsert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Upsert'
type Repository_Upsert_Call[T any, U repository.IEntityIDPtr[T]] struct {
	*mock.Call
}

// Upsert is a helper method to define mock.On call
//   - ctx context.Context
//   - entity U
//   - opt ...*repository.QueryOptions
func (_e *Repository_Expecter[T, U]) Upsert(ctx any, entity any, opt ...any) *Repository_Upsert_Call[T, U] {
	return &Repository_Upsert_Call[T, U]{Call: _e.mock.On("Upsert",
		append([]any{ctx, entity}, opt...)...)}
}

func (_c *Repository_Upsert_Call[T, U]) Run(run func(ctx context.Context, entity U, opt ...*repository.QueryOptions)) *Repository_Upsert_Call[T, U] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 U
		if args[1] != nil {
			arg1 = args[1].(U)
		}
		var arg2 []*repository.QueryOptions
		var variadicArgs []*repository.QueryOptions
		if len(args) > 2 {
			variadicArgs = args[2].([]*repository.QueryOptions)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *Repository_Upsert_Call[T, U]) Return(err error) *Repository_Upsert_Call[T, U] {
	_c.Call.Return(err)
	return _c
}

func (_c *Repository_Upsert_Call[T, U]) RunAndReturn(run func(ctx context.Context, entity U, opt ...*repository.QueryOptions) error) *Repository_Upsert_Call[T, U] {
	_c.Call.Return(run)
	return _c
}

// UpsertMany provides a mock function for the type Repository
func (_mock *Repository[T, U]) UpsertMany(ctx context.Context, entities []U, opt ...*repository.QueryOptions) error {
	var tmpRet mock.Arguments
	if len(opt) > 0 {
		tmpRet = _mock.Called(ctx, entities, opt)
	} else {
		tmpRet = _mock.Called(ctx, entities)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for UpsertMany")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []U, ...*repository.QueryOptions) error); ok {
		r0 = returnFunc(ctx, entities, opt...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Repository_UpsertMany_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpsertMany'
type Repository_UpsertMany_Call[T any, U repository.IEntityIDPtr[T]] struct {
	*mock.Call
}

// UpsertMany is a helper method to define mock.On call
//   - ctx context.Context
//   - entities []U
//   - opt ...*repository.QueryOptions
func (_e *Repository_Expecter[T, U]) UpsertMany(ctx any, entities any, opt ...any) *Repository_UpsertMany_Call[T, U] {
	return &Repository_UpsertMany_Call[T, U]{Call: _e.mock.On("UpsertMany",
		append([]any{ctx, entities}, opt...)...)}
}

func (_c *Repository_UpsertMany_Call[T, U]) Run(run func(ctx context.Context, entities []U, opt ...*repository.QueryOptions)) *Repository_UpsertMany_Call[T, U] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []U
		if args[1] != nil {
			arg1 = args[1].([]U)
		}
		var arg2 []*repository.QueryOptions
		var variadicArgs []*repository.QueryOptions
		if len(args) > 2 {
			variadicArgs = args[2].([]*repository.QueryOptions)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *Repository_UpsertMany_Call[T, U]) Return(err error) *Repository_UpsertMany_Call[T, U] {
	_c.Call.Return(err)
	return _c
}

func (_c *Repository_UpsertMany_Call[T, U]) RunAndReturn(run func(ctx context.Context, entities []U, opt ...*repository.QueryOptions) error) *Repository_UpsertMany_Call[T, U] {
	_c.Call.Return(run)
	return _c
}

// UpsertOne provides a mock function for the type Repository
func (_mock *Repository[T, U]) UpsertOne(ctx context.Context, filter interface{}, update U) error {
	ret := _mock.Called(ctx, filter, update)

	if len(ret) == 0 {
		panic("no return value specified for UpsertOne")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, interface{}, U) error); ok {
		r0 = returnFunc(ctx, filter, update)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Repository_UpsertOne_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpsertOne'
type Repository_UpsertOne_Call[T any, U repository.IEntityIDPtr[T]] struct {
	*mock.Call
}

// UpsertOne is a helper method to define mock.On call
//   - ctx context.Context
//   - filter interface{}
//   - update U
func (_e *Repository_Expecter[T, U]) UpsertOne(ctx any, filter any, update any) *Repository_UpsertOne_Call[T, U] {
	return &Repository_UpsertOne_Call[T, U]{Call: _e.mock.On("UpsertOne", ctx, filter, update)}
}

func (_c *Repository_UpsertOne_Call[T, U]) Run(run func(ctx context.Context, filter interface{}, update U)) *Repository_UpsertOne_Call[T, U] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 interface{}
		if args[1] != nil {
			arg1 = args[1].(interface{})
		}
		var arg2 U
		if args[2] != nil {
			arg2 = args[2].(U)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Repository_UpsertOne_Call[T, U]) Return(err error) *Repository_UpsertOne_Call[T, U] {
	_c.Call.Return(err)
	return _c
}

func (_c *Repository_UpsertOne_Call[T, U]) RunAndReturn(run func(ctx context.Context, filter interface{}, update U) error) *Repository_UpsertOne_Call[T, U] {
	_c.Call.Return(run)
	return _c
}

// WithTransaction provides a mock function for the type Repository
func (_mock *Repository[T, U]) WithTransaction(ctx context.Context, f func(ctx context.Context) (interface{}, error)) (interface{}, error) {
	ret := _mock.Called(ctx, f)

	if len(ret) == 0 {
		panic("no return value specified for WithTransaction")
	}

	var r0 interface{}
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, func(ctx context.Context) (interface{}, error)) (interface{}, error)); ok {
		return returnFunc(ctx, f)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, func(ctx context.Context) (interface{}, error)) interface{}); ok {
		r0 = returnFunc(ctx, f)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, func(ctx context.Context) (interface{}, error)) error); ok {
		r1 = returnFunc(ctx, f)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Repository_WithTransaction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithTransaction'
type Repository_WithTransaction_Call[T any, U repository.IEntityIDPtr[T]] struct {
	*mock.Call
}

// WithTransaction is a helper method to define mock.On call
//   - ctx context.Context
//   - f func(ctx context.Context) (interface{}, error)
func (_e *Repository_Expecter[T, U]) WithTransaction(ctx any, f any) *Repository_WithTransaction_Call[T, U] {
	return &Repository_WithTransaction_Call[T, U]{Call: _e.mock.On("WithTransaction", ctx, f)}
}

func (_c *Repository_WithTransaction_Call[T, U]) Run(run func(ctx context.Context, f func(ctx context.Context) (interface{}, error))) *Repository_WithTransaction_Call[T, U] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 func(ctx context.Context) (interface{}, error)
		if args[1] != nil {
			arg1 = args[1].(func(ctx context.Context) (interface{}, error))
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Repository_WithTransaction_Call[T, U]) Return(ifaceVal interface{}, err error) *Repository_WithTransaction_Call[T, U] {
	_c.Call.Return(ifaceVal, err)
	return _c
}

func (_c *Repository_WithTransaction_Call[T, U]) RunAndReturn(run func(ctx context.Context, f func(ctx context.Context) (interface{}, error)) (interface{}, error)) *Repository_WithTransaction_Call[T, U] {
	_c.Call.Return(run)
	return _c
}
