// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewIDistrCacheRepository creates a new instance of IDistrCacheRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIDistrCacheRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *IDistrCacheRepository {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &IDistrCacheRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// IDistrCacheRepository is an autogenerated mock type for the IDistrCacheRepository type
type IDistrCacheRepository struct {
	mock.Mock
}

type IDistrCacheRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *IDistrCacheRepository) EXPECT() *IDistrCacheRepository_Expecter {
	return &IDistrCacheRepository_Expecter{mock: &_m.Mock}
}

// Add provides a mock function for the type IDistrCacheRepository
func (_mock *IDistrCacheRepository) Add(key string, value []byte) error {
	ret := _mock.Called(key, value)

	if len(ret) == 0 {
		panic("no return value specified for Add")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, []byte) error); ok {
		r0 = returnFunc(key, value)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// IDistrCacheRepository_Add_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Add'
type IDistrCacheRepository_Add_Call struct {
	*mock.Call
}

// Add is a helper method to define mock.On call
//   - key string
//   - value []byte
func (_e *IDistrCacheRepository_Expecter) Add(key any, value any) *IDistrCacheRepository_Add_Call {
	return &IDistrCacheRepository_Add_Call{Call: _e.mock.On("Add", key, value)}
}

func (_c *IDistrCacheRepository_Add_Call) Run(run func(key string, value []byte)) *IDistrCacheRepository_Add_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []byte
		if args[1] != nil {
			arg1 = args[1].([]byte)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *IDistrCacheRepository_Add_Call) Return(err error) *IDistrCacheRepository_Add_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *IDistrCacheRepository_Add_Call) RunAndReturn(run func(key string, value []byte) error) *IDistrCacheRepository_Add_Call {
	_c.Call.Return(run)
	return _c
}

// AddFor provides a mock function for the type IDistrCacheRepository
func (_mock *IDistrCacheRepository) AddFor(key string, value []byte, ttl time.Duration) error {
	ret := _mock.Called(key, value, ttl)

	if len(ret) == 0 {
		panic("no return value specified for AddFor")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, []byte, time.Duration) error); ok {
		r0 = returnFunc(key, value, ttl)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// IDistrCacheRepository_AddFor_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddFor'
type IDistrCacheRepository_AddFor_Call struct {
	*mock.Call
}

// AddFor is a helper method to define mock.On call
//   - key string
//   - value []byte
//   - ttl time.Duration
func (_e *IDistrCacheRepository_Expecter) AddFor(key any, value any, ttl any) *IDistrCacheRepository_AddFor_Call {
	return &IDistrCacheRepository_AddFor_Call{Call: _e.mock.On("AddFor", key, value, ttl)}
}

func (_c *IDistrCacheRepository_AddFor_Call) Run(run func(key string, value []byte, ttl time.Duration)) *IDistrCacheRepository_AddFor_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []byte
		if args[1] != nil {
			arg1 = args[1].([]byte)
		}
		var arg2 time.Duration
		if args[2] != nil {
			arg2 = args[2].(time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *IDistrCacheRepository_AddFor_Call) Return(err error) *IDistrCacheRepository_AddFor_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *IDistrCacheRepository_AddFor_Call) RunAndReturn(run func(key string, value []byte, ttl time.Duration) error) *IDistrCacheRepository_AddFor_Call {
	_c.Call.Return(run)
	return _c
}

// CompareAndSwap provides a mock function for the type IDistrCacheRepository
func (_mock *IDistrCacheRepository) CompareAndSwap(key string, handler func(value []byte) ([]byte, error)) error {
	ret := _mock.Called(key, handler)

	if len(ret) == 0 {
		panic("no return value specified for CompareAndSwap")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, func(value []byte) ([]byte, error)) error); ok {
		r0 = returnFunc(key, handler)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// IDistrCacheRepository_CompareAndSwap_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CompareAndSwap'
type IDistrCacheRepository_CompareAndSwap_Call struct {
	*mock.Call
}

// CompareAndSwap is a helper method to define mock.On call
//   - key string
//   - handler func(value []byte) ([]byte, error)
func (_e *IDistrCacheRepository_Expecter) CompareAndSwap(key any, handler any) *IDistrCacheRepository_CompareAndSwap_Call {
	return &IDistrCacheRepository_CompareAndSwap_Call{Call: _e.mock.On("CompareAndSwap", key, handler)}
}

func (_c *IDistrCacheRepository_CompareAndSwap_Call) Run(run func(key string, handler func(value []byte) ([]byte, error))) *IDistrCacheRepository_CompareAndSwap_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 func(value []byte) ([]byte, error)
		if args[1] != nil {
			arg1 = args[1].(func(value []byte) ([]byte, error))
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *IDistrCacheRepository_CompareAndSwap_Call) Return(err error) *IDistrCacheRepository_CompareAndSwap_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *IDistrCacheRepository_CompareAndSwap_Call) RunAndReturn(run func(key string, handler func(value []byte) ([]byte, error)) error) *IDistrCacheRepository_CompareAndSwap_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type IDistrCacheRepository
func (_mock *IDistrCacheRepository) Delete(key string) error {
	ret := _mock.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(key)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// IDistrCacheRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type IDistrCacheRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - key string
func (_e *IDistrCacheRepository_Expecter) Delete(key any) *IDistrCacheRepository_Delete_Call {
	return &IDistrCacheRepository_Delete_Call{Call: _e.mock.On("Delete", key)}
}

func (_c *IDistrCacheRepository_Delete_Call) Run(run func(key string)) *IDistrCacheRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *IDistrCacheRepository_Delete_Call) Return(err error) *IDistrCacheRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *IDistrCacheRepository_Delete_Call) RunAndReturn(run func(key string) error) *IDistrCacheRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Exist provides a mock function for the type IDistrCacheRepository
func (_mock *IDistrCacheRepository) Exist(key string) bool {
	ret := _mock.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for Exist")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(string) bool); ok {
		r0 = returnFunc(key)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// IDistrCacheRepository_Exist_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exist'
type IDistrCacheRepository_Exist_Call struct {
	*mock.Call
}

// Exist is a helper method to define mock.On call
//   - key string
func (_e *IDistrCacheRepository_Expecter) Exist(key any) *IDistrCacheRepository_Exist_Call {
	return &IDistrCacheRepository_Exist_Call{Call: _e.mock.On("Exist", key)}
}

func (_c *IDistrCacheRepository_Exist_Call) Run(run func(key string)) *IDistrCacheRepository_Exist_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *IDistrCacheRepository_Exist_Call) Return(b bool) *IDistrCacheRepository_Exist_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *IDistrCacheRepository_Exist_Call) RunAndReturn(run func(key string) bool) *IDistrCacheRepository_Exist_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type IDistrCacheRepository
func (_mock *IDistrCacheRepository) Get(key string) ([]byte, error) {
	ret := _mock.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) ([]byte, error)); ok {
		return returnFunc(key)
	}
	if returnFunc, ok := ret.Get(0).(func(string) []byte); ok {
		r0 = returnFunc(key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(key)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// IDistrCacheRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type IDistrCacheRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - key string
func (_e *IDistrCacheRepository_Expecter) Get(key any) *IDistrCacheRepository_Get_Call {
	return &IDistrCacheRepository_Get_Call{Call: _e.mock.On("Get", key)}
}

func (_c *IDistrCacheRepository_Get_Call) Run(run func(key string)) *IDistrCacheRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *IDistrCacheRepository_Get_Call) Return(bytes []byte, err error) *IDistrCacheRepository_Get_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *IDistrCacheRepository_Get_Call) RunAndReturn(run func(key string) ([]byte, error)) *IDistrCacheRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetWithFlags provides a mock function for the type IDistrCacheRepository
func (_mock *IDistrCacheRepository) GetWithFlags(key string) ([]byte, uint32, error) {
	ret := _mock.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for GetWithFlags")
	}

	var r0 []byte
	var r1 uint32
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(string) ([]byte, uint32, error)); ok {
		return returnFunc(key)
	}
	if returnFunc, ok := ret.Get(0).(func(string) []byte); ok {
		r0 = returnFunc(key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) uint32); ok {
		r1 = returnFunc(key)
	} else {
		r1 = ret.Get(1).(uint32)
	}
	if returnFunc, ok := ret.Get(2).(func(string) error); ok {
		r2 = returnFunc(key)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// IDistrCacheRepository_GetWithFlags_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetWithFlags'
type IDistrCacheRepository_GetWithFlags_Call struct {
	*mock.Call
}

// GetWithFlags is a helper method to define mock.On call
//   - key string
func (_e *IDistrCacheRepository_Expecter) GetWithFlags(key any) *IDistrCacheRepository_GetWithFlags_Call {
	return &IDistrCacheRepository_GetWithFlags_Call{Call: _e.mock.On("GetWithFlags", key)}
}

func (_c *IDistrCacheRepository_GetWithFlags_Call) Run(run func(key string)) *IDistrCacheRepository_GetWithFlags_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *IDistrCacheRepository_GetWithFlags_Call) Return(data []byte, flags uint32, err error) *IDistrCacheRepository_GetWithFlags_Call {
	_c.Call.Return(data, flags, err)
	return _c
}

func (_c *IDistrCacheRepository_GetWithFlags_Call) RunAndReturn(run func(key string) ([]byte, uint32, error)) *IDistrCacheRepository_GetWithFlags_Call {
	_c.Call.Return(run)
	return _c
}

// Reset provides a mock function for the type IDistrCacheRepository
func (_mock *IDistrCacheRepository) Reset() {
	_mock.Called()
	return
}

// IDistrCacheRepository_Reset_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Reset'
type IDistrCacheRepository_Reset_Call struct {
	*mock.Call
}

// Reset is a helper method to define mock.On call
func (_e *IDistrCacheRepository_Expecter) Reset() *IDistrCacheRepository_Reset_Call {
	return &IDistrCacheRepository_Reset_Call{Call: _e.mock.On("Reset")}
}

func (_c *IDistrCacheRepository_Reset_Call) Run(run func()) *IDistrCacheRepository_Reset_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *IDistrCacheRepository_Reset_Call) Return() *IDistrCacheRepository_Reset_Call {
	_c.Call.Return()
	return _c
}

func (_c *IDistrCacheRepository_Reset_Call) RunAndReturn(run func()) *IDistrCacheRepository_Reset_Call {
	_c.Run(run)
	return _c
}

// Set provides a mock function for the type IDistrCacheRepository
func (_mock *IDistrCacheRepository) Set(key string, value []byte) error {
	ret := _mock.Called(key, value)

	if len(ret) == 0 {
		panic("no return value specified for Set")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, []byte) error); ok {
		r0 = returnFunc(key, value)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// IDistrCacheRepository_Set_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Set'
type IDistrCacheRepository_Set_Call struct {
	*mock.Call
}

// Set is a helper method to define mock.On call
//   - key string
//   - value []byte
func (_e *IDistrCacheRepository_Expecter) Set(key any, value any) *IDistrCacheRepository_Set_Call {
	return &IDistrCacheRepository_Set_Call{Call: _e.mock.On("Set", key, value)}
}

func (_c *IDistrCacheRepository_Set_Call) Run(run func(key string, value []byte)) *IDistrCacheRepository_Set_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []byte
		if args[1] != nil {
			arg1 = args[1].([]byte)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *IDistrCacheRepository_Set_Call) Return(err error) *IDistrCacheRepository_Set_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *IDistrCacheRepository_Set_Call) RunAndReturn(run func(key string, value []byte) error) *IDistrCacheRepository_Set_Call {
	_c.Call.Return(run)
	return _c
}

// SetFor provides a mock function for the type IDistrCacheRepository
func (_mock *IDistrCacheRepository) SetFor(key string, value []byte, ttl time.Duration) error {
	ret := _mock.Called(key, value, ttl)

	if len(ret) == 0 {
		panic("no return value specified for SetFor")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, []byte, time.Duration) error); ok {
		r0 = returnFunc(key, value, ttl)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// IDistrCacheRepository_SetFor_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetFor'
type IDistrCacheRepository_SetFor_Call struct {
	*mock.Call
}

// SetFor is a helper method to define mock.On call
//   - key string
//   - value []byte
//   - ttl time.Duration
func (_e *IDistrCacheRepository_Expecter) SetFor(key any, value any, ttl any) *IDistrCacheRepository_SetFor_Call {
	return &IDistrCacheRepository_SetFor_Call{Call: _e.mock.On("SetFor", key, value, ttl)}
}

func (_c *IDistrCacheRepository_SetFor_Call) Run(run func(key string, value []byte, ttl time.Duration)) *IDistrCacheRepository_SetFor_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []byte
		if args[1] != nil {
			arg1 = args[1].([]byte)
		}
		var arg2 time.Duration
		if args[2] != nil {
			arg2 = args[2].(time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *IDistrCacheRepository_SetFor_Call) Return(err error) *IDistrCacheRepository_SetFor_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *IDistrCacheRepository_SetFor_Call) RunAndReturn(run func(key string, value []byte, ttl time.Duration) error) *IDistrCacheRepository_SetFor_Call {
	_c.Call.Return(run)
	return _c
}

// SetForWithFlags provides a mock function for the type IDistrCacheRepository
func (_mock *IDistrCacheRepository) SetForWithFlags(key string, value []byte, flags uint32, ttl time.Duration) error {
	ret := _mock.Called(key, value, flags, ttl)

	if len(ret) == 0 {
		panic("no return value specified for SetForWithFlags")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, []byte, uint32, time.Duration) error); ok {
		r0 = returnFunc(key, value, flags, ttl)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// IDistrCacheRepository_SetForWithFlags_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetForWithFlags'
type IDistrCacheRepository_SetForWithFlags_Call struct {
	*mock.Call
}

// SetForWithFlags is a helper method to define mock.On call
//   - key string
//   - value []byte
//   - flags uint32
//   - ttl time.Duration
func (_e *IDistrCacheRepository_Expecter) SetForWithFlags(key any, value any, flags any, ttl any) *IDistrCacheRepository_SetForWithFlags_Call {
	return &IDistrCacheRepository_SetForWithFlags_Call{Call: _e.mock.On("SetForWithFlags", key, value, flags, ttl)}
}

func (_c *IDistrCacheRepository_SetForWithFlags_Call) Run(run func(key string, value []byte, flags uint32, ttl time.Duration)) *IDistrCacheRepository_SetForWithFlags_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []byte
		if args[1] != nil {
			arg1 = args[1].([]byte)
		}
		var arg2 uint32
		if args[2] != nil {
			arg2 = args[2].(uint32)
		}
		var arg3 time.Duration
		if args[3] != nil {
			arg3 = args[3].(time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *IDistrCacheRepository_SetForWithFlags_Call) Return(err error) *IDistrCacheRepository_SetForWithFlags_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *IDistrCacheRepository_SetForWithFlags_Call) RunAndReturn(run func(key string, value []byte, flags uint32, ttl time.Duration) error) *IDistrCacheRepository_SetForWithFlags_Call {
	_c.Call.Return(run)
	return _c
}

// SetWithFlags provides a mock function for the type IDistrCacheRepository
func (_mock *IDistrCacheRepository) SetWithFlags(key string, value []byte, flags uint32) error {
	ret := _mock.Called(key, value, flags)

	if len(ret) == 0 {
		panic("no return value specified for SetWithFlags")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, []byte, uint32) error); ok {
		r0 = returnFunc(key, value, flags)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// IDistrCacheRepository_SetWithFlags_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetWithFlags'
type IDistrCacheRepository_SetWithFlags_Call struct {
	*mock.Call
}

// SetWithFlags is a helper method to define mock.On call
//   - key string
//   - value []byte
//   - flags uint32
func (_e *IDistrCacheRepository_Expecter) SetWithFlags(key any, value any, flags any) *IDistrCacheRepository_SetWithFlags_Call {
	return &IDistrCacheRepository_SetWithFlags_Call{Call: _e.mock.On("SetWithFlags", key, value, flags)}
}

func (_c *IDistrCacheRepository_SetWithFlags_Call) Run(run func(key string, value []byte, flags uint32)) *IDistrCacheRepository_SetWithFlags_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []byte
		if args[1] != nil {
			arg1 = args[1].([]byte)
		}
		var arg2 uint32
		if args[2] != nil {
			arg2 = args[2].(uint32)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *IDistrCacheRepository_SetWithFlags_Call) Return(err error) *IDistrCacheRepository_SetWithFlags_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *IDistrCacheRepository_SetWithFlags_Call) RunAndReturn(run func(key string, value []byte, flags uint32) error) *IDistrCacheRepository_SetWithFlags_Call {
	_c.Call.Return(run)
	return _c
}
