// Code generated by mockery v2.36.0. DO NOT EDIT.

package mocks

import (
	time "time"

	mock "github.com/stretchr/testify/mock"
)

// IExpiringCacheRepository is an autogenerated mock type for the IExpiringCacheRepository type
type IExpiringCacheRepository struct {
	mock.Mock
}

type IExpiringCacheRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *IExpiringCacheRepository) EXPECT() *IExpiringCacheRepository_Expecter {
	return &IExpiringCacheRepository_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function with given fields: key
func (_m *IExpiringCacheRepository) Delete(key string) error {
	ret := _m.Called(key)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(key)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// IExpiringCacheRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type IExpiringCacheRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - key string
func (_e *IExpiringCacheRepository_Expecter) Delete(key interface{}) *IExpiringCacheRepository_Delete_Call {
	return &IExpiringCacheRepository_Delete_Call{Call: _e.mock.On("Delete", key)}
}

func (_c *IExpiringCacheRepository_Delete_Call) Run(run func(key string)) *IExpiringCacheRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *IExpiringCacheRepository_Delete_Call) Return(_a0 error) *IExpiringCacheRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *IExpiringCacheRepository_Delete_Call) RunAndReturn(run func(string) error) *IExpiringCacheRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: key
func (_m *IExpiringCacheRepository) Get(key string) ([]byte, error) {
	ret := _m.Called(key)

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]byte, error)); ok {
		return rf(key)
	}
	if rf, ok := ret.Get(0).(func(string) []byte); ok {
		r0 = rf(key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IExpiringCacheRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type IExpiringCacheRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - key string
func (_e *IExpiringCacheRepository_Expecter) Get(key interface{}) *IExpiringCacheRepository_Get_Call {
	return &IExpiringCacheRepository_Get_Call{Call: _e.mock.On("Get", key)}
}

func (_c *IExpiringCacheRepository_Get_Call) Run(run func(key string)) *IExpiringCacheRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *IExpiringCacheRepository_Get_Call) Return(_a0 []byte, _a1 error) *IExpiringCacheRepository_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *IExpiringCacheRepository_Get_Call) RunAndReturn(run func(string) ([]byte, error)) *IExpiringCacheRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Reset provides a mock function with given fields:
func (_m *IExpiringCacheRepository) Reset() {
	_m.Called()
}

// IExpiringCacheRepository_Reset_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Reset'
type IExpiringCacheRepository_Reset_Call struct {
	*mock.Call
}

// Reset is a helper method to define mock.On call
func (_e *IExpiringCacheRepository_Expecter) Reset() *IExpiringCacheRepository_Reset_Call {
	return &IExpiringCacheRepository_Reset_Call{Call: _e.mock.On("Reset")}
}

func (_c *IExpiringCacheRepository_Reset_Call) Run(run func()) *IExpiringCacheRepository_Reset_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *IExpiringCacheRepository_Reset_Call) Return() *IExpiringCacheRepository_Reset_Call {
	_c.Call.Return()
	return _c
}

func (_c *IExpiringCacheRepository_Reset_Call) RunAndReturn(run func()) *IExpiringCacheRepository_Reset_Call {
	_c.Call.Return(run)
	return _c
}

// Set provides a mock function with given fields: key, value
func (_m *IExpiringCacheRepository) Set(key string, value []byte) error {
	ret := _m.Called(key, value)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, []byte) error); ok {
		r0 = rf(key, value)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// IExpiringCacheRepository_Set_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Set'
type IExpiringCacheRepository_Set_Call struct {
	*mock.Call
}

// Set is a helper method to define mock.On call
//   - key string
//   - value []byte
func (_e *IExpiringCacheRepository_Expecter) Set(key interface{}, value interface{}) *IExpiringCacheRepository_Set_Call {
	return &IExpiringCacheRepository_Set_Call{Call: _e.mock.On("Set", key, value)}
}

func (_c *IExpiringCacheRepository_Set_Call) Run(run func(key string, value []byte)) *IExpiringCacheRepository_Set_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].([]byte))
	})
	return _c
}

func (_c *IExpiringCacheRepository_Set_Call) Return(_a0 error) *IExpiringCacheRepository_Set_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *IExpiringCacheRepository_Set_Call) RunAndReturn(run func(string, []byte) error) *IExpiringCacheRepository_Set_Call {
	_c.Call.Return(run)
	return _c
}

// SetFor provides a mock function with given fields: key, value, ttl
func (_m *IExpiringCacheRepository) SetFor(key string, value []byte, ttl time.Duration) error {
	ret := _m.Called(key, value, ttl)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, []byte, time.Duration) error); ok {
		r0 = rf(key, value, ttl)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// IExpiringCacheRepository_SetFor_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetFor'
type IExpiringCacheRepository_SetFor_Call struct {
	*mock.Call
}

// SetFor is a helper method to define mock.On call
//   - key string
//   - value []byte
//   - ttl time.Duration
func (_e *IExpiringCacheRepository_Expecter) SetFor(key interface{}, value interface{}, ttl interface{}) *IExpiringCacheRepository_SetFor_Call {
	return &IExpiringCacheRepository_SetFor_Call{Call: _e.mock.On("SetFor", key, value, ttl)}
}

func (_c *IExpiringCacheRepository_SetFor_Call) Run(run func(key string, value []byte, ttl time.Duration)) *IExpiringCacheRepository_SetFor_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].([]byte), args[2].(time.Duration))
	})
	return _c
}

func (_c *IExpiringCacheRepository_SetFor_Call) Return(_a0 error) *IExpiringCacheRepository_SetFor_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *IExpiringCacheRepository_SetFor_Call) RunAndReturn(run func(string, []byte, time.Duration) error) *IExpiringCacheRepository_SetFor_Call {
	_c.Call.Return(run)
	return _c
}

// NewIExpiringCacheRepository creates a new instance of IExpiringCacheRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIExpiringCacheRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *IExpiringCacheRepository {
	mock := &IExpiringCacheRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
