// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewIExpiringCacheRepository creates a new instance of IExpiringCacheRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIExpiringCacheRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *IExpiringCacheRepository {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &IExpiringCacheRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// IExpiringCacheRepository is an autogenerated mock type for the IExpiringCacheRepository type
type IExpiringCacheRepository struct {
	mock.Mock
}

type IExpiringCacheRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *IExpiringCacheRepository) EXPECT() *IExpiringCacheRepository_Expecter {
	return &IExpiringCacheRepository_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function for the type IExpiringCacheRepository
func (_mock *IExpiringCacheRepository) Delete(key string) error {
	ret := _mock.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(key)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// IExpiringCacheRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type IExpiringCacheRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - key string
func (_e *IExpiringCacheRepository_Expecter) Delete(key any) *IExpiringCacheRepository_Delete_Call {
	return &IExpiringCacheRepository_Delete_Call{Call: _e.mock.On("Delete", key)}
}

func (_c *IExpiringCacheRepository_Delete_Call) Run(run func(key string)) *IExpiringCacheRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *IExpiringCacheRepository_Delete_Call) Return(err error) *IExpiringCacheRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *IExpiringCacheRepository_Delete_Call) RunAndReturn(run func(key string) error) *IExpiringCacheRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type IExpiringCacheRepository
func (_mock *IExpiringCacheRepository) Get(key string) ([]byte, error) {
	ret := _mock.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) ([]byte, error)); ok {
		return returnFunc(key)
	}
	if returnFunc, ok := ret.Get(0).(func(string) []byte); ok {
		r0 = returnFunc(key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(key)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// IExpiringCacheRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type IExpiringCacheRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - key string
func (_e *IExpiringCacheRepository_Expecter) Get(key any) *IExpiringCacheRepository_Get_Call {
	return &IExpiringCacheRepository_Get_Call{Call: _e.mock.On("Get", key)}
}

func (_c *IExpiringCacheRepository_Get_Call) Run(run func(key string)) *IExpiringCacheRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *IExpiringCacheRepository_Get_Call) Return(bytes []byte, err error) *IExpiringCacheRepository_Get_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *IExpiringCacheRepository_Get_Call) RunAndReturn(run func(key string) ([]byte, error)) *IExpiringCacheRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Reset provides a mock function for the type IExpiringCacheRepository
func (_mock *IExpiringCacheRepository) Reset() {
	_mock.Called()
	return
}

// IExpiringCacheRepository_Reset_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Reset'
type IExpiringCacheRepository_Reset_Call struct {
	*mock.Call
}

// Reset is a helper method to define mock.On call
func (_e *IExpiringCacheRepository_Expecter) Reset() *IExpiringCacheRepository_Reset_Call {
	return &IExpiringCacheRepository_Reset_Call{Call: _e.mock.On("Reset")}
}

func (_c *IExpiringCacheRepository_Reset_Call) Run(run func()) *IExpiringCacheRepository_Reset_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *IExpiringCacheRepository_Reset_Call) Return() *IExpiringCacheRepository_Reset_Call {
	_c.Call.Return()
	return _c
}

func (_c *IExpiringCacheRepository_Reset_Call) RunAndReturn(run func()) *IExpiringCacheRepository_Reset_Call {
	_c.Run(run)
	return _c
}

// Set provides a mock function for the type IExpiringCacheRepository
func (_mock *IExpiringCacheRepository) Set(key string, value []byte) error {
	ret := _mock.Called(key, value)

	if len(ret) == 0 {
		panic("no return value specified for Set")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, []byte) error); ok {
		r0 = returnFunc(key, value)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// IExpiringCacheRepository_Set_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Set'
type IExpiringCacheRepository_Set_Call struct {
	*mock.Call
}

// Set is a helper method to define mock.On call
//   - key string
//   - value []byte
func (_e *IExpiringCacheRepository_Expecter) Set(key any, value any) *IExpiringCacheRepository_Set_Call {
	return &IExpiringCacheRepository_Set_Call{Call: _e.mock.On("Set", key, value)}
}

func (_c *IExpiringCacheRepository_Set_Call) Run(run func(key string, value []byte)) *IExpiringCacheRepository_Set_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []byte
		if args[1] != nil {
			arg1 = args[1].([]byte)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *IExpiringCacheRepository_Set_Call) Return(err error) *IExpiringCacheRepository_Set_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *IExpiringCacheRepository_Set_Call) RunAndReturn(run func(key string, value []byte) error) *IExpiringCacheRepository_Set_Call {
	_c.Call.Return(run)
	return _c
}

// SetFor provides a mock function for the type IExpiringCacheRepository
func (_mock *IExpiringCacheRepository) SetFor(key string, value []byte, ttl time.Duration) error {
	ret := _mock.Called(key, value, ttl)

	if len(ret) == 0 {
		panic("no return value specified for SetFor")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, []byte, time.Duration) error); ok {
		r0 = returnFunc(key, value, ttl)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// IExpiringCacheRepository_SetFor_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetFor'
type IExpiringCacheRepository_SetFor_Call struct {
	*mock.Call
}

// SetFor is a helper method to define mock.On call
//   - key string
//   - value []byte
//   - ttl time.Duration
func (_e *IExpiringCacheRepository_Expecter) SetFor(key any, value any, ttl any) *IExpiringCacheRepository_SetFor_Call {
	return &IExpiringCacheRepository_SetFor_Call{Call: _e.mock.On("SetFor", key, value, ttl)}
}

func (_c *IExpiringCacheRepository_SetFor_Call) Run(run func(key string, value []byte, ttl time.Duration)) *IExpiringCacheRepository_SetFor_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []byte
		if args[1] != nil {
			arg1 = args[1].([]byte)
		}
		var arg2 time.Duration
		if args[2] != nil {
			arg2 = args[2].(time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *IExpiringCacheRepository_SetFor_Call) Return(err error) *IExpiringCacheRepository_SetFor_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *IExpiringCacheRepository_SetFor_Call) RunAndReturn(run func(key string, value []byte, ttl time.Duration) error) *IExpiringCacheRepository_SetFor_Call {
	_c.Call.Return(run)
	return _c
}
