// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMarshaler creates a new instance of Marshaler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMarshaler[T any](t interface {
	mock.TestingT
	Cleanup(func())
}) *Marshaler[T] {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &Marshaler[T]{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// Marshaler is an autogenerated mock type for the Marshaler type
type Marshaler[T any] struct {
	mock.Mock
}

type Marshaler_Expecter[T any] struct {
	mock *mock.Mock
}

func (_m *Marshaler[T]) EXPECT() *Marshaler_Expecter[T] {
	return &Marshaler_Expecter[T]{mock: &_m.Mock}
}

// Marshal provides a mock function for the type Marshaler
func (_mock *Marshaler[T]) Marshal(v T) ([]byte, error) {
	ret := _mock.Called(v)

	if len(ret) == 0 {
		panic("no return value specified for Marshal")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(T) ([]byte, error)); ok {
		return returnFunc(v)
	}
	if returnFunc, ok := ret.Get(0).(func(T) []byte); ok {
		r0 = returnFunc(v)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(T) error); ok {
		r1 = returnFunc(v)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Marshaler_Marshal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Marshal'
type Marshaler_Marshal_Call[T any] struct {
	*mock.Call
}

// Marshal is a helper method to define mock.On call
//   - v T
func (_e *Marshaler_Expecter[T]) Marshal(v any) *Marshaler_Marshal_Call[T] {
	return &Marshaler_Marshal_Call[T]{Call: _e.mock.On("Marshal", v)}
}

func (_c *Marshaler_Marshal_Call[T]) Run(run func(v T)) *Marshaler_Marshal_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 T
		if args[0] != nil {
			arg0 = args[0].(T)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Marshaler_Marshal_Call[T]) Return(bytes []byte, err error) *Marshaler_Marshal_Call[T] {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *Marshaler_Marshal_Call[T]) RunAndReturn(run func(v T) ([]byte, error)) *Marshaler_Marshal_Call[T] {
	_c.Call.Return(run)
	return _c
}

// Unmarshal provides a mock function for the type Marshaler
func (_mock *Marshaler[T]) Unmarshal(data []byte) (T, error) {
	ret := _mock.Called(data)

	if len(ret) == 0 {
		panic("no return value specified for Unmarshal")
	}

	var r0 T
	var r1 error
	if returnFunc, ok := ret.Get(0).(func([]byte) (T, error)); ok {
		return returnFunc(data)
	}
	if returnFunc, ok := ret.Get(0).(func([]byte) T); ok {
		r0 = returnFunc(data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(T)
		}
	}
	if returnFunc, ok := ret.Get(1).(func([]byte) error); ok {
		r1 = returnFunc(data)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Marshaler_Unmarshal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Unmarshal'
type Marshaler_Unmarshal_Call[T any] struct {
	*mock.Call
}

// Unmarshal is a helper method to define mock.On call
//   - data []byte
func (_e *Marshaler_Expecter[T]) Unmarshal(data any) *Marshaler_Unmarshal_Call[T] {
	return &Marshaler_Unmarshal_Call[T]{Call: _e.mock.On("Unmarshal", data)}
}

func (_c *Marshaler_Unmarshal_Call[T]) Run(run func(data []byte)) *Marshaler_Unmarshal_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []byte
		if args[0] != nil {
			arg0 = args[0].([]byte)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Marshaler_Unmarshal_Call[T]) Return(v T, err error) *Marshaler_Unmarshal_Call[T] {
	_c.Call.Return(v, err)
	return _c
}

func (_c *Marshaler_Unmarshal_Call[T]) RunAndReturn(run func(data []byte) (T, error)) *Marshaler_Unmarshal_Call[T] {
	_c.Call.Return(run)
	return _c
}
