// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepository[T any](t interface {
	mock.TestingT
	Cleanup(func())
}) *Repository[T] {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &Repository[T]{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// Repository is an autogenerated mock type for the Repository type
type Repository[T any] struct {
	mock.Mock
}

type Repository_Expecter[T any] struct {
	mock *mock.Mock
}

func (_m *Repository[T]) EXPECT() *Repository_Expecter[T] {
	return &Repository_Expecter[T]{mock: &_m.Mock}
}

// Delete provides a mock function for the type Repository
func (_mock *Repository[T]) Delete(key string) error {
	ret := _mock.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(key)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Repository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type Repository_Delete_Call[T any] struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - key string
func (_e *Repository_Expecter[T]) Delete(key any) *Repository_Delete_Call[T] {
	return &Repository_Delete_Call[T]{Call: _e.mock.On("Delete", key)}
}

func (_c *Repository_Delete_Call[T]) Run(run func(key string)) *Repository_Delete_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Repository_Delete_Call[T]) Return(err error) *Repository_Delete_Call[T] {
	_c.Call.Return(err)
	return _c
}

func (_c *Repository_Delete_Call[T]) RunAndReturn(run func(key string) error) *Repository_Delete_Call[T] {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type Repository
func (_mock *Repository[T]) Get(key string) (T, error) {
	ret := _mock.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 T
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (T, error)); ok {
		return returnFunc(key)
	}
	if returnFunc, ok := ret.Get(0).(func(string) T); ok {
		r0 = returnFunc(key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(T)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(key)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Repository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type Repository_Get_Call[T any] struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - key string
func (_e *Repository_Expecter[T]) Get(key any) *Repository_Get_Call[T] {
	return &Repository_Get_Call[T]{Call: _e.mock.On("Get", key)}
}

func (_c *Repository_Get_Call[T]) Run(run func(key string)) *Repository_Get_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Repository_Get_Call[T]) Return(v T, err error) *Repository_Get_Call[T] {
	_c.Call.Return(v, err)
	return _c
}

func (_c *Repository_Get_Call[T]) RunAndReturn(run func(key string) (T, error)) *Repository_Get_Call[T] {
	_c.Call.Return(run)
	return _c
}

// Reset provides a mock function for the type Repository
func (_mock *Repository[T]) Reset() {
	_mock.Called()
	return
}

// Repository_Reset_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Reset'
type Repository_Reset_Call[T any] struct {
	*mock.Call
}

// Reset is a helper method to define mock.On call
func (_e *Repository_Expecter[T]) Reset() *Repository_Reset_Call[T] {
	return &Repository_Reset_Call[T]{Call: _e.mock.On("Reset")}
}

func (_c *Repository_Reset_Call[T]) Run(run func()) *Repository_Reset_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Repository_Reset_Call[T]) Return() *Repository_Reset_Call[T] {
	_c.Call.Return()
	return _c
}

func (_c *Repository_Reset_Call[T]) RunAndReturn(run func()) *Repository_Reset_Call[T] {
	_c.Run(run)
	return _c
}

// Set provides a mock function for the type Repository
func (_mock *Repository[T]) Set(key string, value T) error {
	ret := _mock.Called(key, value)

	if len(ret) == 0 {
		panic("no return value specified for Set")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, T) error); ok {
		r0 = returnFunc(key, value)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Repository_Set_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Set'
type Repository_Set_Call[T any] struct {
	*mock.Call
}

// Set is a helper method to define mock.On call
//   - key string
//   - value T
func (_e *Repository_Expecter[T]) Set(key any, value any) *Repository_Set_Call[T] {
	return &Repository_Set_Call[T]{Call: _e.mock.On("Set", key, value)}
}

func (_c *Repository_Set_Call[T]) Run(run func(key string, value T)) *Repository_Set_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 T
		if args[1] != nil {
			arg1 = args[1].(T)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Repository_Set_Call[T]) Return(err error) *Repository_Set_Call[T] {
	_c.Call.Return(err)
	return _c
}

func (_c *Repository_Set_Call[T]) RunAndReturn(run func(key string, value T) error) *Repository_Set_Call[T] {
	_c.Call.Return(run)
	return _c
}

// SetFor provides a mock function for the type Repository
func (_mock *Repository[T]) SetFor(key string, value T, ttl time.Duration) error {
	ret := _mock.Called(key, value, ttl)

	if len(ret) == 0 {
		panic("no return value specified for SetFor")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, T, time.Duration) error); ok {
		r0 = returnFunc(key, value, ttl)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Repository_SetFor_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetFor'
type Repository_SetFor_Call[T any] struct {
	*mock.Call
}

// SetFor is a helper method to define mock.On call
//   - key string
//   - value T
//   - ttl time.Duration
func (_e *Repository_Expecter[T]) SetFor(key any, value any, ttl any) *Repository_SetFor_Call[T] {
	return &Repository_SetFor_Call[T]{Call: _e.mock.On("SetFor", key, value, ttl)}
}

func (_c *Repository_SetFor_Call[T]) Run(run func(key string, value T, ttl time.Duration)) *Repository_SetFor_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 T
		if args[1] != nil {
			arg1 = args[1].(T)
		}
		var arg2 time.Duration
		if args[2] != nil {
			arg2 = args[2].(time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Repository_SetFor_Call[T]) Return(err error) *Repository_SetFor_Call[T] {
	_c.Call.Return(err)
	return _c
}

func (_c *Repository_SetFor_Call[T]) RunAndReturn(run func(key string, value T, ttl time.Duration) error) *Repository_SetFor_Call[T] {
	_c.Call.Return(run)
	return _c
}
