// Code generated by go-enum DO NOT EDIT.
// Version:
// Revision:
// Build Date:
// Built By:

package log

import (
	"fmt"
)

const (
	// SortFieldTimestamp is a SortField of type Timestamp.
	SortFieldTimestamp SortField = iota
	// SortFieldLevel is a SortField of type Level.
	SortFieldLevel
	// SortFieldReqID is a SortField of type ReqID.
	SortFieldReqID
)

const _SortFieldName = "TimestampLevelReqID"

var _SortFieldMap = map[SortField]string{
	SortFieldTimestamp: _SortFieldName[0:9],
	SortFieldLevel:     _SortFieldName[9:14],
	SortFieldReqID:     _SortFieldName[14:19],
}

// String implements the Stringer interface.
func (x SortField) String() string {
	if str, ok := _SortFieldMap[x]; ok {
		return str
	}
	return fmt.Sprintf("SortField(%d)", x)
}

var _SortFieldValue = map[string]SortField{
	_SortFieldName[0:9]:   SortFieldTimestamp,
	_SortFieldName[9:14]:  SortFieldLevel,
	_SortFieldName[14:19]: SortFieldReqID,
}

// ParseSortField attempts to convert a string to a SortField.
func ParseSortField(name string) (SortField, error) {
	if x, ok := _SortFieldValue[name]; ok {
		return x, nil
	}
	return SortField(0), fmt.Errorf("%s is not a valid SortField", name)
}

const (
	// SortOrderASC is a SortOrder of type ASC.
	SortOrderASC SortOrder = iota
	// SortOrderDESC is a SortOrder of type DESC.
	SortOrderDESC
)

const _SortOrderName = "ASCDESC"

var _SortOrderMap = map[SortOrder]string{
	SortOrderASC:  _SortOrderName[0:3],
	SortOrderDESC: _SortOrderName[3:7],
}

// String implements the Stringer interface.
func (x SortOrder) String() string {
	if str, ok := _SortOrderMap[x]; ok {
		return str
	}
	return fmt.Sprintf("SortOrder(%d)", x)
}

var _SortOrderValue = map[string]SortOrder{
	_SortOrderName[0:3]: SortOrderASC,
	_SortOrderName[3:7]: SortOrderDESC,
}

// ParseSortOrder attempts to convert a string to a SortOrder.
func ParseSortOrder(name string) (SortOrder, error) {
	if x, ok := _SortOrderValue[name]; ok {
		return x, nil
	}
	return SortOrder(0), fmt.Errorf("%s is not a valid SortOrder", name)
}
