// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"time"

	"github.com/bldsoft/gost/cache/v2"
	mock "github.com/stretchr/testify/mock"
)

// NewIDistrCacheRepository creates a new instance of IDistrCacheRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIDistrCacheRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *IDistrCacheRepository {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &IDistrCacheRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// IDistrCacheRepository is an autogenerated mock type for the IDistrCacheRepository type
type IDistrCacheRepository struct {
	mock.Mock
}

type IDistrCacheRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *IDistrCacheRepository) EXPECT() *IDistrCacheRepository_Expecter {
	return &IDistrCacheRepository_Expecter{mock: &_m.Mock}
}

// Add provides a mock function for the type IDistrCacheRepository
func (_mock *IDistrCacheRepository) Add(key string, val []byte, opts ...cache.ItemF) error {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(key, val, opts)
	} else {
		tmpRet = _mock.Called(key, val)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Add")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, []byte, ...cache.ItemF) error); ok {
		r0 = returnFunc(key, val, opts...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// IDistrCacheRepository_Add_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Add'
type IDistrCacheRepository_Add_Call struct {
	*mock.Call
}

// Add is a helper method to define mock.On call
//   - key string
//   - val []byte
//   - opts ...cache.ItemF
func (_e *IDistrCacheRepository_Expecter) Add(key any, val any, opts ...any) *IDistrCacheRepository_Add_Call {
	return &IDistrCacheRepository_Add_Call{Call: _e.mock.On("Add",
		append([]any{key, val}, opts...)...)}
}

func (_c *IDistrCacheRepository_Add_Call) Run(run func(key string, val []byte, opts ...cache.ItemF)) *IDistrCacheRepository_Add_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []byte
		if args[1] != nil {
			arg1 = args[1].([]byte)
		}
		var arg2 []cache.ItemF
		var variadicArgs []cache.ItemF
		if len(args) > 2 {
			variadicArgs = args[2].([]cache.ItemF)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *IDistrCacheRepository_Add_Call) Return(err error) *IDistrCacheRepository_Add_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *IDistrCacheRepository_Add_Call) RunAndReturn(run func(key string, val []byte, opts ...cache.ItemF) error) *IDistrCacheRepository_Add_Call {
	_c.Call.Return(run)
	return _c
}

// AddOrGet provides a mock function for the type IDistrCacheRepository
func (_mock *IDistrCacheRepository) AddOrGet(key string, val []byte, opts ...cache.ItemF) (*cache.Item, bool, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(key, val, opts)
	} else {
		tmpRet = _mock.Called(key, val)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for AddOrGet")
	}

	var r0 *cache.Item
	var r1 bool
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(string, []byte, ...cache.ItemF) (*cache.Item, bool, error)); ok {
		return returnFunc(key, val, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(string, []byte, ...cache.ItemF) *cache.Item); ok {
		r0 = returnFunc(key, val, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cache.Item)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, []byte, ...cache.ItemF) bool); ok {
		r1 = returnFunc(key, val, opts...)
	} else {
		r1 = ret.Get(1).(bool)
	}
	if returnFunc, ok := ret.Get(2).(func(string, []byte, ...cache.ItemF) error); ok {
		r2 = returnFunc(key, val, opts...)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// IDistrCacheRepository_AddOrGet_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddOrGet'
type IDistrCacheRepository_AddOrGet_Call struct {
	*mock.Call
}

// AddOrGet is a helper method to define mock.On call
//   - key string
//   - val []byte
//   - opts ...cache.ItemF
func (_e *IDistrCacheRepository_Expecter) AddOrGet(key any, val any, opts ...any) *IDistrCacheRepository_AddOrGet_Call {
	return &IDistrCacheRepository_AddOrGet_Call{Call: _e.mock.On("AddOrGet",
		append([]any{key, val}, opts...)...)}
}

func (_c *IDistrCacheRepository_AddOrGet_Call) Run(run func(key string, val []byte, opts ...cache.ItemF)) *IDistrCacheRepository_AddOrGet_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []byte
		if args[1] != nil {
			arg1 = args[1].([]byte)
		}
		var arg2 []cache.ItemF
		var variadicArgs []cache.ItemF
		if len(args) > 2 {
			variadicArgs = args[2].([]cache.ItemF)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *IDistrCacheRepository_AddOrGet_Call) Return(i *cache.Item, added bool, err error) *IDistrCacheRepository_AddOrGet_Call {
	_c.Call.Return(i, added, err)
	return _c
}

func (_c *IDistrCacheRepository_AddOrGet_Call) RunAndReturn(run func(key string, val []byte, opts ...cache.ItemF) (*cache.Item, bool, error)) *IDistrCacheRepository_AddOrGet_Call {
	_c.Call.Return(run)
	return _c
}

// CompareAndSwap provides a mock function for the type IDistrCacheRepository
func (_mock *IDistrCacheRepository) CompareAndSwap(key string, handler func(value *cache.Item) (*cache.Item, error), sleepDur ...time.Duration) error {
	var tmpRet mock.Arguments
	if len(sleepDur) > 0 {
		tmpRet = _mock.Called(key, handler, sleepDur)
	} else {
		tmpRet = _mock.Called(key, handler)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for CompareAndSwap")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, func(value *cache.Item) (*cache.Item, error), ...time.Duration) error); ok {
		r0 = returnFunc(key, handler, sleepDur...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// IDistrCacheRepository_CompareAndSwap_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CompareAndSwap'
type IDistrCacheRepository_CompareAndSwap_Call struct {
	*mock.Call
}

// CompareAndSwap is a helper method to define mock.On call
//   - key string
//   - handler func(value *cache.Item) (*cache.Item, error)
//   - sleepDur ...time.Duration
func (_e *IDistrCacheRepository_Expecter) CompareAndSwap(key any, handler any, sleepDur ...any) *IDistrCacheRepository_CompareAndSwap_Call {
	return &IDistrCacheRepository_CompareAndSwap_Call{Call: _e.mock.On("CompareAndSwap",
		append([]any{key, handler}, sleepDur...)...)}
}

func (_c *IDistrCacheRepository_CompareAndSwap_Call) Run(run func(key string, handler func(value *cache.Item) (*cache.Item, error), sleepDur ...time.Duration)) *IDistrCacheRepository_CompareAndSwap_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 func(value *cache.Item) (*cache.Item, error)
		if args[1] != nil {
			arg1 = args[1].(func(value *cache.Item) (*cache.Item, error))
		}
		var arg2 []time.Duration
		var variadicArgs []time.Duration
		if len(args) > 2 {
			variadicArgs = args[2].([]time.Duration)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *IDistrCacheRepository_CompareAndSwap_Call) Return(err error) *IDistrCacheRepository_CompareAndSwap_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *IDistrCacheRepository_CompareAndSwap_Call) RunAndReturn(run func(key string, handler func(value *cache.Item) (*cache.Item, error), sleepDur ...time.Duration) error) *IDistrCacheRepository_CompareAndSwap_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type IDistrCacheRepository
func (_mock *IDistrCacheRepository) Delete(key string) error {
	ret := _mock.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(key)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// IDistrCacheRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type IDistrCacheRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - key string
func (_e *IDistrCacheRepository_Expecter) Delete(key any) *IDistrCacheRepository_Delete_Call {
	return &IDistrCacheRepository_Delete_Call{Call: _e.mock.On("Delete", key)}
}

func (_c *IDistrCacheRepository_Delete_Call) Run(run func(key string)) *IDistrCacheRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *IDistrCacheRepository_Delete_Call) Return(err error) *IDistrCacheRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *IDistrCacheRepository_Delete_Call) RunAndReturn(run func(key string) error) *IDistrCacheRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Exist provides a mock function for the type IDistrCacheRepository
func (_mock *IDistrCacheRepository) Exist(key string) bool {
	ret := _mock.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for Exist")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(string) bool); ok {
		r0 = returnFunc(key)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// IDistrCacheRepository_Exist_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exist'
type IDistrCacheRepository_Exist_Call struct {
	*mock.Call
}

// Exist is a helper method to define mock.On call
//   - key string
func (_e *IDistrCacheRepository_Expecter) Exist(key any) *IDistrCacheRepository_Exist_Call {
	return &IDistrCacheRepository_Exist_Call{Call: _e.mock.On("Exist", key)}
}

func (_c *IDistrCacheRepository_Exist_Call) Run(run func(key string)) *IDistrCacheRepository_Exist_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *IDistrCacheRepository_Exist_Call) Return(b bool) *IDistrCacheRepository_Exist_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *IDistrCacheRepository_Exist_Call) RunAndReturn(run func(key string) bool) *IDistrCacheRepository_Exist_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type IDistrCacheRepository
func (_mock *IDistrCacheRepository) Get(key string) (*cache.Item, error) {
	ret := _mock.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *cache.Item
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*cache.Item, error)); ok {
		return returnFunc(key)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *cache.Item); ok {
		r0 = returnFunc(key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cache.Item)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(key)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// IDistrCacheRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type IDistrCacheRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - key string
func (_e *IDistrCacheRepository_Expecter) Get(key any) *IDistrCacheRepository_Get_Call {
	return &IDistrCacheRepository_Get_Call{Call: _e.mock.On("Get", key)}
}

func (_c *IDistrCacheRepository_Get_Call) Run(run func(key string)) *IDistrCacheRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *IDistrCacheRepository_Get_Call) Return(item *cache.Item, err error) *IDistrCacheRepository_Get_Call {
	_c.Call.Return(item, err)
	return _c
}

func (_c *IDistrCacheRepository_Get_Call) RunAndReturn(run func(key string) (*cache.Item, error)) *IDistrCacheRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Set provides a mock function for the type IDistrCacheRepository
func (_mock *IDistrCacheRepository) Set(key string, val []byte, opts ...cache.ItemF) error {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(key, val, opts)
	} else {
		tmpRet = _mock.Called(key, val)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Set")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, []byte, ...cache.ItemF) error); ok {
		r0 = returnFunc(key, val, opts...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// IDistrCacheRepository_Set_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Set'
type IDistrCacheRepository_Set_Call struct {
	*mock.Call
}

// Set is a helper method to define mock.On call
//   - key string
//   - val []byte
//   - opts ...cache.ItemF
func (_e *IDistrCacheRepository_Expecter) Set(key any, val any, opts ...any) *IDistrCacheRepository_Set_Call {
	return &IDistrCacheRepository_Set_Call{Call: _e.mock.On("Set",
		append([]any{key, val}, opts...)...)}
}

func (_c *IDistrCacheRepository_Set_Call) Run(run func(key string, val []byte, opts ...cache.ItemF)) *IDistrCacheRepository_Set_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []byte
		if args[1] != nil {
			arg1 = args[1].([]byte)
		}
		var arg2 []cache.ItemF
		var variadicArgs []cache.ItemF
		if len(args) > 2 {
			variadicArgs = args[2].([]cache.ItemF)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *IDistrCacheRepository_Set_Call) Return(err error) *IDistrCacheRepository_Set_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *IDistrCacheRepository_Set_Call) RunAndReturn(run func(key string, val []byte, opts ...cache.ItemF) error) *IDistrCacheRepository_Set_Call {
	_c.Call.Return(run)
	return _c
}
