// Code generated by go-enum DO NOT EDIT.
// Version:
// Revision:
// Build Date:
// Built By:

package alert

import (
	"errors"
	"fmt"
)

const (
	// SeverityLow is a SeverityLevel of type SeverityLow.
	SeverityLow SeverityLevel = iota
	// SeverityMedium is a SeverityLevel of type SeverityMedium.
	SeverityMedium
	// SeverityHigh is a SeverityLevel of type SeverityHigh.
	SeverityHigh
	// SeverityCritical is a SeverityLevel of type SeverityCritical.
	SeverityCritical
)

var ErrInvalidSeverityLevel = errors.New("not a valid SeverityLevel")

const _SeverityLevelName = "SeverityLowSeverityMediumSeverityHighSeverityCritical"

var _SeverityLevelMap = map[SeverityLevel]string{
	SeverityLow:      _SeverityLevelName[0:11],
	SeverityMedium:   _SeverityLevelName[11:25],
	SeverityHigh:     _SeverityLevelName[25:37],
	SeverityCritical: _SeverityLevelName[37:53],
}

// String implements the Stringer interface.
func (x SeverityLevel) String() string {
	if str, ok := _SeverityLevelMap[x]; ok {
		return str
	}
	return fmt.Sprintf("SeverityLevel(%d)", x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x SeverityLevel) IsValid() bool {
	_, ok := _SeverityLevelMap[x]
	return ok
}

var _SeverityLevelValue = map[string]SeverityLevel{
	_SeverityLevelName[0:11]:  SeverityLow,
	_SeverityLevelName[11:25]: SeverityMedium,
	_SeverityLevelName[25:37]: SeverityHigh,
	_SeverityLevelName[37:53]: SeverityCritical,
}

// ParseSeverityLevel attempts to convert a string to a SeverityLevel.
func ParseSeverityLevel(name string) (SeverityLevel, error) {
	if x, ok := _SeverityLevelValue[name]; ok {
		return x, nil
	}
	return SeverityLevel(0), fmt.Errorf("%s is %w", name, ErrInvalidSeverityLevel)
}
