//go:build integration_test

package mongo

import (
	"context"
	"os"
	"testing"

	"github.com/bldsoft/gost/config"
	"github.com/bldsoft/gost/log"
	"github.com/stretchr/testify/assert"
	"go.mongodb.org/mongo-driver/bson"
)

const testCollection = "test_collection"

var (
	db *Storage
)

type testEntity struct {
	EntityID `bson:",inline"`
	Field    string
}

func TestMain(m *testing.M) {
	log.SetLogLevel("")

	var cfg Config
	config.ReadConfig(&cfg, "")

	db = NewStorage(cfg)
	db.Connect()

	code := m.Run()

	ctx := context.Background()
	_, _ = db.Db.Collection(testCollection).DeleteMany(ctx, bson.M{})
	_ = db.Disconnect(ctx)

	os.Exit(code)
}

func testRepository(t *testing.T) (context.Context, Repository[testEntity, *testEntity]) {
	t.Helper()
	ctx := context.Background()
	rep := NewRepository[testEntity](db, testCollection)
	t.Cleanup(func() {
		clearTestCollection(t, ctx)
	})
	return ctx, rep
}

func clearTestCollection(t *testing.T, ctx context.Context) {
	t.Helper()
	_, err := db.Db.Collection(testCollection).DeleteMany(ctx, bson.M{})
	assert.NoError(t, err)
}

func TestBaseRepository_InsertOrReplace(t *testing.T) {
	tests := []struct {
		name         string
		prepare      func(t *testing.T, ctx context.Context, rep Repository[testEntity, *testEntity]) *testEntity
		wantInserted bool
	}{
		{
			name: "insert new entity without id",
			prepare: func(t *testing.T, ctx context.Context, rep Repository[testEntity, *testEntity]) *testEntity {
				return &testEntity{Field: "value1"}
			},
			wantInserted: true,
		},
		{
			name: "insert entity with generated id when document does not exist",
			prepare: func(t *testing.T, ctx context.Context, rep Repository[testEntity, *testEntity]) *testEntity {
				e := &testEntity{Field: "value2"}
				e.GenerateID()
				return e
			},
			wantInserted: true,
		},
		{
			name: "replace existing entity",
			prepare: func(t *testing.T, ctx context.Context, rep Repository[testEntity, *testEntity]) *testEntity {
				e := &testEntity{Field: "initial"}
				assert.NoError(t, rep.Insert(ctx, e))
				e.Field = "updated"
				return e
			},
			wantInserted: false,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			ctx, rep := testRepository(t)
			entity := tt.prepare(t, ctx, rep)

			inserted, err := rep.InsertOrReplace(ctx, entity)
			assert.NoError(t, err)
			assert.Equal(t, tt.wantInserted, inserted)
		})
	}
}

func TestBaseRepository_InsertOrReplaceMany(t *testing.T) {
	t.Run("empty slice does nothing", func(t *testing.T) {
		ctx, rep := testRepository(t)

		err := rep.InsertOrReplaceMany(ctx, []*testEntity{})
		assert.NoError(t, err)

		count, err := rep.Collection().CountDocuments(ctx, bson.M{})
		assert.NoError(t, err)
		assert.EqualValues(t, 0, count)
	})

	t.Run("insert and replace multiple entities", func(t *testing.T) {
		ctx, rep := testRepository(t)

		existing1 := &testEntity{Field: "e1"}
		existing2 := &testEntity{Field: "e2"}
		assert.NoError(t, rep.Insert(ctx, existing1))
		assert.NoError(t, rep.Insert(ctx, existing2))

		newEntity := &testEntity{Field: "new"}
		existing1.Field = "e1_updated"
		existing2.Field = "e2_updated"

		err := rep.InsertOrReplaceMany(ctx, []*testEntity{
			newEntity,
			existing1,
			existing2,
		})
		assert.NoError(t, err)

		// existing entities should be updated
		got1, err := rep.FindByID(ctx, existing1.StringID())
		assert.NoError(t, err)
		assert.Equal(t, "e1_updated", got1.Field)

		got2, err := rep.FindByID(ctx, existing2.StringID())
		assert.NoError(t, err)
		assert.Equal(t, "e2_updated", got2.Field)

		// new entity should be inserted (search by field value, id is generated by MongoDB)
		foundNew, err := rep.Find(ctx, bson.M{"field": "new"})
		assert.NoError(t, err)
		assert.Len(t, foundNew, 1)
	})
}
